RpcTools 5.x Project: BaseRpcModule Class Reference
BaseRpcModule Class Reference
Public Member Functions
Create ()
Register base propertys and profiles for Device .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Member Functions inherited from IPSModule
__construct ($InstanceID)
Create ()
Destroy ()
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
ApplyChanges ()
ReceiveData ($JSONString)
ForwardData ($JSONString)
RequestAction ($Ident, $Value)
GetConfigurationForm ()
GetConfigurationForParent ()
Translate ($Text)
GetReferenceList ()
Protected Member Functions
ValidateConfiguration ()
Validate current configuration.
SetStatus ($Status)
Set module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
Get device state.
SetDeviceState ($State)
Set device state.
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the module propertys.
SetProps (int $props, $Update=true, $doApply=true)
Setup module propertys.
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
Update module status variables by propertys.
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Override in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
Get status variable value by ident.
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
Set status variable value by ident.
CreateVarByProp ($Prop)
Create status variable by module property.
CreateVarByIdent ($Ident, $CheckIdent=true)
Create status variable by ident.
ValidIdent ($Ident, $CheckProp=false)
Checks if ident valid.
CreateMissedProfile ($name)
Is called if a profile missed.
GetPropDef ($Ident)
Returns status variable definition.
GetModuleName ($name, $host)
Is called once if module created or Configuration valid.
IsLastInstance ($guid)
Checks if more instances created with then given module ID.
Protected Member Functions inherited from IPSModule
GetIDForIdent ($Ident)
RegisterPropertyBoolean ($Name, $DefaultValue)
RegisterPropertyInteger ($Name, $DefaultValue)
RegisterPropertyFloat ($Name, $DefaultValue)
RegisterPropertyString ($Name, $DefaultValue)
RegisterAttributeBoolean ($Name, $DefaultValue)
RegisterAttributeInteger ($Name, $DefaultValue)
RegisterAttributeFloat ($Name, $DefaultValue)
RegisterAttributeString ($Name, $DefaultValue)
RegisterTimer ($Ident, $Milliseconds, $ScriptText)
SetTimerInterval ($Name, $Milliseconds)
RegisterScript ($Ident, $Name, $Content, $Position)
RegisterVariableBoolean ($Ident, $Name, $Profile, $Position)
RegisterVariableInteger ($Ident, $Name, $Profile, $Position)
RegisterVariableFloat ($Ident, $Name, $Profile, $Position)
RegisterVariableString ($Ident, $Name, $Profile, $Position)
UnregisterVariable ($Ident)
MaintainVariable ($Ident, $Name, $Type, $Profile, $Position, $Keep)
EnableAction ($Ident)
DisableAction ($Ident)
MaintainAction ($Ident, $Action)
ReadPropertyBoolean ($Name)
ReadPropertyInteger ($Name)
ReadPropertyFloat ($Name)
ReadPropertyString ($Name)
ReadAttributeBoolean ($Name)
ReadAttributeInteger ($Name)
ReadAttributeFloat ($Name)
ReadAttributeString ($Name)
WriteAttributeBoolean ($Name, $Value)
WriteAttributeInteger ($Name, $Value)
WriteAttributeFloat ($Name, $Value)
WriteAttributeString ($Name, $Value)
SendDataToParent ($Data)
SendDataToChildren ($Data)
ConnectParent ($ModuleID)
RequireParent ($ModuleID)
ForceParent ($ModuleID)
SetStatus ($Status)
SetSummary ($Summary)
SetBuffer ($Name, $Data)
GetBufferList ()
GetBuffer ($Name)
SendDebug ($Message, $Data, $Format)
RegisterMessage ($SenderID, $Message)
UnregisterMessage ($SenderID, $Message)
SetReceiveDataFilter ($RequiredRegexMatch)
SetForwardDataFilter ($RequiredRegexMatch)
RegisterReference (int $ID)
UnregisterReference (int $ID)
Protected Attributes
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Override this to configure Timers for Module.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable.
$online =null
if not checked then $online=null, true if online false if host not reachable
$state =null
State cache if not checked then $state=null, 0=connected | 1=disconnected | 2=error.
$status = null
Status cache if not checked then $status=null.
$prop_names = []
Contains a List of valid Propertys.
Protected Attributes inherited from IPSModule
$InstanceID
Detailed Description
Author
Xavier
Definition at line 12 of file rpc_module.inc.
Member Function Documentation
ApplyChanges()
BaseRpcModule::ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
See also
IPSModule::ApplyChanges()
Returns
bool True if no property, inside this function, changed
Definition at line 45 of file rpc_module.inc.
References RunUpdate(), IPSModule\SendDebug(), SetStatus(), UpdateProps(), and ValidateConfiguration().
ApplyHost()
BaseRpcModule::ApplyHost ($host, $doApply = true) protected
Checks and Setup given host.
Parameters
string $host Host url/ip to check
bool $doApply If true changes are applyed to module configuration
Definition at line 360 of file rpc_module.inc.
References SetStatus().
Referenced by ValidateConfiguration().
CheckOnline()
BaseRpcModule::CheckOnline () protected
Checks if host online and setup devicestate.
Returns
bool True if device is online
Definition at line 244 of file rpc_module.inc.
References $online, IPSModule\ReadPropertyString(), and SetDeviceState().
Referenced by IPSRpcModule\CreateApi(), IPSRpcModule\RunUpdate(), SetStatus(), StartTimer(), and MediaRpc\WriteValue().
Create()
BaseRpcModule::Create ()
Register base propertys and profiles for Device .
See also
IPSModule::Create()
Definition at line 17 of file rpc_module.inc.
References IPSModule\RegisterMessage(), UTILS\RegisterProfileIntegerEx(), IPSModule\RegisterPropertyBoolean(), IPSModule\RegisterPropertyInteger(), IPSModule\RegisterPropertyString(), IPSModule\RegisterTimer(), and IPSModule\Translate().
CreateMissedProfile()
BaseRpcModule::CreateMissedProfile ($name) protected
Is called if a profile missed.
Parameters
string $name Create missing profile
Returns
bool True if profile created
Note
Override in your own Module
Definition at line 457 of file rpc_module.inc.
Referenced by CreateVarByIdent().
CreateVarByIdent()
BaseRpcModule::CreateVarByIdent ($Ident, $CheckIdent = true) protected
Create status variable by ident.
Parameters
string $Ident Variable ident to create
bool $CheckIdent Check Ident is Valid
Returns
int Variable Instance ID
Definition at line 408 of file rpc_module.inc.
References CreateMissedProfile(), DEF_ACTION, DEF_ICON, DEF_NAME, DEF_POS, DEF_PROFILE, DEF_TYPE, IPSModule\EnableAction(), IPSModule\GetIDForIdent(), GetPropDef(), IPSModule\RegisterVariableBoolean(), IPSModule\RegisterVariableFloat(), IPSModule\RegisterVariableInteger(), IPSModule\RegisterVariableString(), IPSModule\SendDebug(), IPSModule\Translate(), and ValidIdent().
Referenced by CreateVarByProp(), SetValueByIdent(), and UpdateDeviceProps().
CreateVarByProp()
BaseRpcModule::CreateVarByProp ($Prop) protected
Create status variable by module property.
Parameters
int $Prop Property to create Variable for
Returns
int Variable Instance ID
Definition at line 399 of file rpc_module.inc.
References CreateVarByIdent().
Destroy()
BaseRpcModule::Destroy ()
Cleanup unsused profiles if is last instance .
See also
IPSModule::Destroy()
Definition at line 67 of file rpc_module.inc.
References IsLastInstance().
GetConfigurationForm()
BaseRpcModule::GetConfigurationForm ()
Load formular and handle Timers and Login fields .
See also
BaseRpcModule::GetConfigurationForm()
Definition at line 88 of file rpc_module.inc.
References MODULEDIR.
GetDeviceState()
BaseRpcModule::GetDeviceState () protected
Get device state.
Returns
int State of device 0=connected|1=disconnected|2=error
Definition at line 226 of file rpc_module.inc.
References $state, IPSModule\GetIDForIdent(), IPSModule\RegisterVariableInteger(), and IPSModule\Translate().
Referenced by IPSRpcModule\CreateApi(), IPSRpcModule\RunUpdate(), StartTimer(), and MediaRpc\WriteValue().
GetModuleName()
BaseRpcModule::GetModuleName ($name, $host) protected
Is called once if module created or Configuration valid.
Parameters
string $name The name of device
string $host The host for device
Returns
string The displayed module name
Note
Override in your own Module
Definition at line 482 of file rpc_module.inc.
Referenced by IPSRpcModule\ApplyHost().
GetPropDef()
BaseRpcModule::GetPropDef ($Ident) abstract protected
Returns status variable definition.
Parameters
string $Ident Variable ident to get Definition
Returns
null|array Status variable config array or null if ident not valid
Note
Must Override in your own Module
Referenced by CreateVarByIdent(), and ValidIdent().
GetProps()
BaseRpcModule::GetProps () protected
Get the module propertys.
Returns
int
Definition at line 255 of file rpc_module.inc.
References IPSModule\ReadPropertyInteger().
Referenced by MediaRpc\DoUpdate(), SetProps(), and ValidIdent().
GetStatus()
BaseRpcModule::GetStatus () protected
Return current instance status.
Returns
int Instance Status
Definition at line 220 of file rpc_module.inc.
References $status.
GetValueByIdent()
BaseRpcModule::GetValueByIdent ($Ident) protected
Get status variable value by ident.
Parameters
string $Ident Status variable ident to get value from
Returns
NULL|mixed The value for ident or NULL if ident invalid
Definition at line 372 of file rpc_module.inc.
References IPSModule\GetIDForIdent().
IsLastInstance()
BaseRpcModule::IsLastInstance ($guid) protected
Checks if more instances created with then given module ID.
Parameters
string $guid Module ID
Returns
bool True if no more instance created
Definition at line 490 of file rpc_module.inc.
Referenced by MediaRpc\Destroy(), and Destroy().
MessageSink()
BaseRpcModule::MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
See also
IPSModule::MessageSink()
Definition at line 125 of file rpc_module.inc.
References StartTimer().
RequestAction()
BaseRpcModule::RequestAction ($Ident, $Value)
Handle timer update events .
See also
IPSModule::RequestAction()
Returns
bool True if ident processed
Definition at line 115 of file rpc_module.inc.
References RunUpdate().
RunUpdate()
BaseRpcModule::RunUpdate () protected
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
Note
Override in your own Module
Definition at line 354 of file rpc_module.inc.
Referenced by ApplyChanges(), and RequestAction().
SetDeviceState()
BaseRpcModule::SetDeviceState ($State) protected
Set device state.
Parameters
int $State Valid states are 0=connected|1=disconnected|2=error
Definition at line 236 of file rpc_module.inc.
References IPSModule\GetIDForIdent(), IPSModule\RegisterVariableInteger(), and IPSModule\Translate().
Referenced by CheckOnline(), and SetStatus().
SetProps()
BaseRpcModule::SetProps (int $props, $Update = true, $doApply = true) protected
Setup module propertys.
Parameters
int $props Device or Module Propertys
bool $Update If true then autocreate and delete used and unused vars
bool $doApply If true then changes will Apply to Config , false is call comes out from Apply() function
Returns
bool True if Props changes
Definition at line 264 of file rpc_module.inc.
References GetProps(), IPSModule\SendDebug(), and UpdateDeviceProps().
Referenced by MediaRpc\ApplyDeviceProps(), and GenericRpc\ApplyDeviceProps().
SetStatus()
BaseRpcModule::SetStatus ($Status) protected
Set module status .
See also
IPSModule::SetStatus()
Definition at line 211 of file rpc_module.inc.
References CheckOnline(), and SetDeviceState().
Referenced by ApplyChanges(), ApplyHost(), IPSRpcModule\ApplyHost(), IPSRpcModule\CreateApi(), and ValidateConfiguration().
SetValueByIdent()
BaseRpcModule::SetValueByIdent ($Ident, $Value, $force = true, $AutoCreate = true) protected
Set status variable value by ident.
Parameters
string $Ident Variable ident to set value
mixed $Value Data to set
bool $force Set value if changed or not
bool $AutoCreate Create variable if not exists
Returns
bool True if changed or false if ident not found or not changed
Definition at line 382 of file rpc_module.inc.
References CreateVarByIdent(), and IPSModule\GetIDForIdent().
Referenced by MediaRpc\_readValue(), and MediaRpc\_writeValue().
StartTimer()
BaseRpcModule::StartTimer ($delay = 0) protected
Start timer based on BaseRpcModule::$timerDef.
Parameters
number $delay if greater 0 then this will used to setup timer interval
Definition at line 337 of file rpc_module.inc.
References CheckOnline(), GetDeviceState(), IPSModule\ReadPropertyInteger(), and IPSModule\SetTimerInterval().
Referenced by MessageSink(), IPSRpcModule\RunUpdate(), and MediaRpc\WriteValue().
StopTimer()
BaseRpcModule::StopTimer () protected
Stop current Timer.
Definition at line 330 of file rpc_module.inc.
References IPSModule\SetTimerInterval().
Referenced by IPSRpcModule\RunUpdate(), and MediaRpc\WriteValue().
UpdateDeviceProps()
BaseRpcModule::UpdateDeviceProps ($props, $AutoCreate = true, $AutoRemove = true) protected
Update module status variables by propertys.
Parameters
int $props Device or Module propertys
bool $AutoCreate if true then auto create missing status variables
bool $AutoRemove if true then remove unused status variables
Returns
bool True if status variables removed or created
Definition at line 281 of file rpc_module.inc.
References CreateVarByIdent(), IPSModule\DisableAction(), IPSModule\GetIDForIdent(), and IPSModule\UnregisterVariable().
Referenced by SetProps().
UpdateProps()
BaseRpcModule::UpdateProps ($doApply = true) protected
Update device property is called from ApplyChanges Override in your own Module.
Parameters
bool $doApply If true then changes are applyed to instance
Returns
bool True is nothing changed
Definition at line 301 of file rpc_module.inc.
Referenced by ApplyChanges().
ValidateConfiguration()
BaseRpcModule::ValidateConfiguration () protected
Validate current configuration.
Returns
bool True if nothing changed and Configuration is valid
Definition at line 181 of file rpc_module.inc.
References ApplyHost(), IPSModule\DisableAction(), IPSModule\EnableAction(), IPSModule\GetIDForIdent(), IPSModule\ReadPropertyBoolean(), IPSModule\ReadPropertyString(), IPSModule\RegisterVariableInteger(), SetStatus(), IPSModule\Translate(), IPSModule\UnregisterVariable(), and ValidateTimers().
Referenced by ApplyChanges().
ValidateTimers()
BaseRpcModule::ValidateTimers () protected
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
Returns
bool True if timers valid
Definition at line 309 of file rpc_module.inc.
References IPSModule\ReadPropertyInteger(), and IPSModule\SendDebug().
Referenced by ValidateConfiguration().
ValidIdent()
BaseRpcModule::ValidIdent ($Ident, $CheckProp = false) protected
Checks if ident valid.
Parameters
string $Ident Variable ident to check
bool $CheckProp If true then checks ident prop is set
Returns
bool
Definition at line 446 of file rpc_module.inc.
References DEF_PROP, GetPropDef(), and GetProps().
Referenced by CreateVarByIdent(), and MediaRpc\WriteValue().
Member Data Documentation
$online
bool null BaseRpcModule::$online =null protected
if not checked then $online=null, true if online false if host not reachable
Definition at line 168 of file rpc_module.inc.
Referenced by CheckOnline().
$prop_names
array BaseRpcModule::$prop_names = [] protected
Contains a List of valid Propertys.
Key = Property value
Value = Property ident name
Note
Must Override in your own Module
Definition at line 474 of file rpc_module.inc.
$requireLogin
array BaseRpcModule::$requireLogin =[false,false] protected
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
if first true then check that Username are given, second true checks for password
Note
Override in your Module to configure require login
Definition at line 152 of file rpc_module.inc.
$showLogin
array BaseRpcModule::$showLogin =[false,false] protected
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
if first true then shows username field in formular, seccond true show password field
Note
Override in your Module to configure show login
Definition at line 159 of file rpc_module.inc.
$showRefreshButton
bool BaseRpcModule::$showRefreshButton =false protected
If true then show config field in formulars to display a refresh button variable.
Note
Override in your Module to configure refresh button
Definition at line 164 of file rpc_module.inc.
$state
int null BaseRpcModule::$state =null protected
State cache if not checked then $state=null, 0=connected | 1=disconnected | 2=error.
Definition at line 172 of file rpc_module.inc.
Referenced by GetDeviceState().
$status
int null BaseRpcModule::$status = null protected
Status cache if not checked then $status=null.
Definition at line 176 of file rpc_module.inc.
Referenced by GetStatus().
$timerDef
array BaseRpcModule::$timerDef =['ONLINE_INTERVAL'=>[0,'s'] protected
Setup the Timers Override this to configure Timers for Module.
ONLINE_INTERVAL checks when device is Online * OFFLINE_INTERVAL checks when device is offline
Parameters for Checks are [0,'s'] first are the minimum value 0 = timer disabled and second are the multiplicator s = seconds, m = minutes and h are hours
Note
Override in your Module to configure Timers
Definition at line 145 of file rpc_module.inc.
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/libs/rpc_module.inc