My Project: FritzStatus Class Reference
FritzStatus Class Reference
Public Member Functions
Create ()
Destroy ()
ApplyChanges ()
RequestAction ($Ident, $Value)
RequestUpdate ()
Public Member Functions inherited from IPSRpcModule
Create ()
ApplyChanges ()
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
GetApi ()
GetApiInfo ()
Public Member Functions inherited from BaseRpcModule
Create ()
ApplyChanges ()
Destroy ()
GetConfigurationForm ()
RequestAction ($Ident, $Value)
Public Attributes
PROP_SPEED_DOWN => 'SPEED_DOWN',PROP_SPEED_UP => 'SPEED_UP',PROP_ISTATE => 'ISTATE',PROP_RECONNECT => 'RECONNECT',PROP_REBOOT => 'REBOOT',PROP_WIFI2G => 'WIFI2G',PROP_WIFI5G => 'WIFI5G',PROP_WIFIGUEST => 'WIFIGUEST',PROP_WIFIGUEST_KEY=>'WIFIGUEST_KEY']
Protected Member Functions
GetDiscoverDeviceOptions ()
GetModuleName ($name, $host)
DoUpdate ()
GetPropDef ($Ident)
Protected Member Functions inherited from IPSRpcModule
DoUpdate ()
RunUpdate ()
StartTimer ($delay=0)
GetDeviceConfig ()
CreateApi ()
CallApi (string $function, array $arguments=[])
GetDiscoverDeviceOptions ()
ApplyHost ($host, $doApply=false)
ReDiscover ()
ApplyDeviceProps ($Props)
GetProps ()
SetProps (int $props, $Update=true)
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
RegisterHook ($Name, bool $Create)
ProcessHookData ()
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
SetStatus ($Status)
GetStatus ()
GetDeviceState ()
SetDeviceState ($State)
CheckOnline ()
ValidateTimers ()
StopTimer ()
StartTimer ($delay=0)
RunUpdate ()
ApplyHost ($host, $doApply=true)
GetValueByIdent ($Ident)
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
CreateVarByProp ($Prop)
CreateVarByIdent ($Ident, $CheckIdent=true)
ValidIdent ($Ident, $CheckProp=false)
CreateMissedProfile ($name)
GetPropDef ($Ident)
GetProps ()
GetModuleName ($name, $host)
IsLastInstance ($guid)
Protected Attributes
$timerDef =['ONLINE_INTERVAL'=>[1,'h']
$requireLogin =[true,true]
$prop_names = [PROP_EXTERNAL_IP =>'EXTERNAL_IP'
Protected Attributes inherited from IPSRpcModule
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
$requireLogin =[false,false]
$showLogin =[true,true]
$online =null
if not checked Null, true if online false if host not reachable
$state =null
State cache 0=connected | 1=disconnected | 2=error.
$status = null
Status cache
$prop_names = []
Contains a List of valid Propertys Key = Property value Value = Property ident name.
Private Member Functions
doSetWLANState ($wlanProp, $state)
doReconnect ()
doReboot ()
doUpdateBoxStatus ()
doUpdateWlanStatus ($id=0)
updateProps ()
Detailed Description
Author
Xavier
Definition at line 8 of file module.php.
Member Function Documentation
ApplyChanges()
FritzStatus::ApplyChanges ()
See also
IPSRpcModule::ApplyChanges()
Definition at line 47 of file module.php.
References BaseRpcModule\GetStatus(), IPSRpcModule\RunUpdate(), and updateProps().
Create()
FritzStatus::Create ()
See also
IPSRpcModule::Create()
Definition at line 13 of file module.php.
References UTILS\RegisterProfileBooleanEx(), and UTILS\RegisterProfileInteger().
Destroy()
FritzStatus::Destroy ()
See also
BaseRpcModule::Destroy()
Definition at line 34 of file module.php.
References BaseRpcModule\IsLastInstance().
doReboot()
FritzStatus::doReboot () private
Definition at line 153 of file module.php.
References IPSRpcModule\CallApi().
Referenced by RequestAction().
doReconnect()
FritzStatus::doReconnect () private
Definition at line 147 of file module.php.
References IPSRpcModule\CallApi().
Referenced by RequestAction().
doSetWLANState()
FritzStatus::doSetWLANState ($wlanProp, $state) private
Definition at line 140 of file module.php.
References BaseRpcModule\$state, IPSRpcModule\CallApi(), IPSRpcModule\CreateApi(), doUpdateWlanStatus(), PROP_WIFI2G, PROP_WIFI5G, and PROP_WIFIGUEST.
Referenced by RequestAction().
DoUpdate()
FritzStatus::DoUpdate () protected
See also
IPSRpcModule::DoUpdate()
Definition at line 107 of file module.php.
References doUpdateBoxStatus(), and doUpdateWlanStatus().
doUpdateBoxStatus()
FritzStatus::doUpdateBoxStatus () private
Definition at line 158 of file module.php.
References IPSRpcModule\CallApi(), and BaseRpcModule\SetValueByIdent().
Referenced by DoUpdate().
doUpdateWlanStatus()
FritzStatus::doUpdateWlanStatus ($id = 0) private
Definition at line 175 of file module.php.
References IPSRpcModule\CallApi(), and BaseRpcModule\SetValueByIdent().
Referenced by doSetWLANState(), and DoUpdate().
GetDiscoverDeviceOptions()
FritzStatus::GetDiscoverDeviceOptions () protected
See also
BaseRpcModule::GetDiscoverDeviceOptions()
Definition at line 85 of file module.php.
References OPT_MINIMIZED, and OPT_SMALCONFIG.
GetModuleName()
FritzStatus::GetModuleName ($name, $host) protected
See also
BaseRpcModule::GetModuleName()
Definition at line 99 of file module.php.
GetPropDef()
FritzStatus::GetPropDef ($Ident) protected
See also
IPSRpcModule::GetPropDef()
Definition at line 116 of file module.php.
References PROP_EXTERNAL_IP, PROP_ISTATE, PROP_REBOOT, PROP_RECONNECT, PROP_SPEED_DOWN, PROP_SPEED_UP, PROP_WIFI2G, PROP_WIFI5G, PROP_WIFIGUEST, and PROP_WIFIGUEST_KEY.
RequestAction()
FritzStatus::RequestAction ($Ident, $Value)
See also
IPSRpcModule::RequestAction()
Definition at line 57 of file module.php.
References doReboot(), doReconnect(), doSetWLANState(), PROP_REBOOT, PROP_RECONNECT, PROP_WIFI2G, PROP_WIFI5G, and PROP_WIFIGUEST.
RequestUpdate()
FritzStatus::RequestUpdate ()
Definition at line 73 of file module.php.
References IPSRpcModule\RunUpdate().
updateProps()
FritzStatus::updateProps () private
Definition at line 196 of file module.php.
References PROP_EXTERNAL_IP, PROP_ISTATE, PROP_REBOOT, PROP_RECONNECT, PROP_SPEED_DOWN, PROP_SPEED_UP, PROP_WIFI2G, PROP_WIFI5G, PROP_WIFIGUEST, PROP_WIFIGUEST_KEY, IPSRpcModule\SetProps(), and BaseRpcModule\SetValueByIdent().
Referenced by ApplyChanges().
Member Data Documentation
$prop_names
array FritzStatus::$prop_names = [PROP_EXTERNAL_IP =>'EXTERNAL_IP' protected
See also
IPSRpcModule::$prop_names
Definition at line 135 of file module.php.
$requireLogin
FritzStatus::$requireLogin =[true,true] protected
Definition at line 79 of file module.php.
$timerDef
FritzStatus::$timerDef =['ONLINE_INTERVAL'=>[1,'h'] protected
Definition at line 78 of file module.php.
PROP_SPEED_DOWN
FritzStatus::PROP_SPEED_DOWN => 'SPEED_DOWN',PROP_SPEED_UP => 'SPEED_UP',PROP_ISTATE => 'ISTATE',PROP_RECONNECT => 'RECONNECT',PROP_REBOOT => 'REBOOT',PROP_WIFI2G => 'WIFI2G',PROP_WIFI5G => 'WIFI5G',PROP_WIFIGUEST => 'WIFIGUEST',PROP_WIFIGUEST_KEY=>'WIFIGUEST_KEY']
Definition at line 135 of file module.php.
Referenced by GetPropDef(), and updateProps().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/FritzStatus/module.php