RpcTools 5.x Project: IPSModule Class Reference
IPSModule Class Reference
Public Member Functions
__construct ($InstanceID)
Create ()
Destroy ()
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
ApplyChanges ()
ReceiveData ($JSONString)
ForwardData ($JSONString)
RequestAction ($Ident, $Value)
GetConfigurationForm ()
GetConfigurationForParent ()
Translate ($Text)
GetReferenceList ()
Protected Member Functions
GetIDForIdent ($Ident)
RegisterPropertyBoolean ($Name, $DefaultValue)
RegisterPropertyInteger ($Name, $DefaultValue)
RegisterPropertyFloat ($Name, $DefaultValue)
RegisterPropertyString ($Name, $DefaultValue)
RegisterAttributeBoolean ($Name, $DefaultValue)
RegisterAttributeInteger ($Name, $DefaultValue)
RegisterAttributeFloat ($Name, $DefaultValue)
RegisterAttributeString ($Name, $DefaultValue)
RegisterTimer ($Ident, $Milliseconds, $ScriptText)
SetTimerInterval ($Name, $Milliseconds)
RegisterScript ($Ident, $Name, $Content, $Position)
RegisterVariableBoolean ($Ident, $Name, $Profile, $Position)
RegisterVariableInteger ($Ident, $Name, $Profile, $Position)
RegisterVariableFloat ($Ident, $Name, $Profile, $Position)
RegisterVariableString ($Ident, $Name, $Profile, $Position)
UnregisterVariable ($Ident)
MaintainVariable ($Ident, $Name, $Type, $Profile, $Position, $Keep)
EnableAction ($Ident)
DisableAction ($Ident)
MaintainAction ($Ident, $Action)
ReadPropertyBoolean ($Name)
ReadPropertyInteger ($Name)
ReadPropertyFloat ($Name)
ReadPropertyString ($Name)
ReadAttributeBoolean ($Name)
ReadAttributeInteger ($Name)
ReadAttributeFloat ($Name)
ReadAttributeString ($Name)
WriteAttributeBoolean ($Name, $Value)
WriteAttributeInteger ($Name, $Value)
WriteAttributeFloat ($Name, $Value)
WriteAttributeString ($Name, $Value)
SendDataToParent ($Data)
SendDataToChildren ($Data)
ConnectParent ($ModuleID)
RequireParent ($ModuleID)
ForceParent ($ModuleID)
SetStatus ($Status)
SetSummary ($Summary)
SetBuffer ($Name, $Data)
GetBufferList ()
GetBuffer ($Name)
SendDebug ($Message, $Data, $Format)
RegisterMessage ($SenderID, $Message)
UnregisterMessage ($SenderID, $Message)
SetReceiveDataFilter ($RequiredRegexMatch)
SetForwardDataFilter ($RequiredRegexMatch)
RegisterReference (int $ID)
UnregisterReference (int $ID)
Protected Attributes
$InstanceID
Detailed Description
Author
IP-Symcon
Definition at line 6 of file IPSModule.php.
Constructor & Destructor Documentation
__construct()
IPSModule::__construct ($InstanceID)
Der Konstruktor wird bei jeglichem Funktionsaufruf aufgerufen und kümmert sich um die Instanzierung. Die Basisklasse nutzt den Konstruktor um z.B. die InstanzID zu setzen.
Parameters
int $InstanceID ID dieser Instanz
Note
Sollen eigene Erweiterungen hinzugefügt werden, muss der Konstruktor von der Basisklasse überschrieben werden.
Definition at line 20 of file IPSModule.php.
Member Function Documentation
ApplyChanges()
IPSModule::ApplyChanges ()
Wird ausgefuehrt, wenn auf der Konfigurationsseite "Uebernehmen" gedrueckt wird und nach dem unittelbaren Erstellen der Instanz.
Note
Die ApplyChanges Funktion wird von IP-Symcon aufgerufen. Sie muss somit von der Basisklasse überschrieben werden, um eigene Erweiterungen hinzuzufügen
Definition at line 398 of file IPSModule.php.
ConnectParent()
IPSModule::ConnectParent ($ModuleID) protected
Die Funktion verbindet die Instanz mit einer vorhandenen uebergeordneten kompatiblen (Parent) Instanz. Sollte diese nicht vorhanden sein, wird diese erstellt und anschliessend verbunden.
Parameters
string $ModuleID GUID der uebergeordneten Instanz
Definition at line 309 of file IPSModule.php.
Create()
IPSModule::Create ()
Im Gegensatz zu Construct wird diese Funktion nur einmalig beim Erstellen der Instanz und Start von IP-Symcon aufgerufen. Deshalb sollten hier Statusvariablen und Modul-Eigenschaften erstellt werden, die das Modul dauerhaft braucht.
Definition at line 25 of file IPSModule.php.
Destroy()
IPSModule::Destroy ()
Diese Funktion wird beim Loeschen der Instanz im laufenden Betrieb und bei Update via "Module Control" aufgerufen. Die Funktion wird nicht beim Beenden von IP-Symcon aufgerufen.
Definition at line 30 of file IPSModule.php.
DisableAction()
IPSModule::DisableAction ($Ident) protected
Deaktiviert die Standardaktion der Statusvariable. Dadurch ist diese in der Visualisierung nicht mehr veraenderbar, sondern kann nur gelesen werden. Sofern EnableAction nicht aufrufen wurde, muss diese Funktion nicht aufgerufen werden, da alle Statusvariablen standardmaessig ohne Standardaktion erstellt werden.
Parameters
string $Ident
Definition at line 194 of file IPSModule.php.
Referenced by BaseRpcModule\UpdateDeviceProps(), and BaseRpcModule\ValidateConfiguration().
EnableAction()
IPSModule::EnableAction ($Ident) protected
Aktiviert die Standardaktion der Statusvariable. Dadurch ist diese in der Visualisierung veraenderbar und kann auch beschrieben werden. Diese Funktion muss aufgerufen werden, da alle Statusvariablen standardmaessig ohne Standardaktion erstellt werden. Sofern die Standardaktion aktiviert ist, muss auf Aenderungsanfragen innerhalb von RequestAction reagiert werden.
Parameters
string $Ident
Definition at line 188 of file IPSModule.php.
Referenced by BaseRpcModule\CreateVarByIdent(), and BaseRpcModule\ValidateConfiguration().
ForceParent()
IPSModule::ForceParent ($ModuleID) protected
Es wird eine Verbindung mit einer kompatiblen uebergeordneten Instanz mit der GUID ModulID forciert. Falls die bisherige Verbindung nicht mit der gewuenschten ModulID uebereinstimmt, wird diese getrennt. Anschliessend wird eine neue Instanz mit der übergordneten ModuleID erstellt und verbunden.
Parameters
string $ModuleID
Definition at line 323 of file IPSModule.php.
ForwardData()
IPSModule::ForwardData ($JSONString)
Diese Funktion wird von IP-Symcon aufgerufen und verarbeitet zugesendete Daten und schickt diese an die übergeordnete Instanz weiter. Daten können über die Funktion SendDataToParent versendet werden. Weitere Informationen zur Datenweiterleitung können unter Datenfluss gefunden werden.
Parameters
string $JSONString Datenpaket im JSON Format
Returns
mixed Resultat der Funktion, welches an die aufrufendene untergeordnete Instanz zurückgegeben wird
Note
Die ForwardData Funktion wird von IP-Symcon aufgerufen. Sie muss somit von der Basisklasse überschrieben werden, um eigene Erweiterungen hinzuzufügen
Definition at line 429 of file IPSModule.php.
GetBuffer()
IPSModule::GetBuffer ($Name) protected
Diese Funktion liefert den Inhalt des Buffers mit dem Namen Name. Wenn der Buffer leer ist, wird ein leerer String zurückgegeben.
Parameters
string $Name Name des Buffers
Returns
string Der Inhalt des Buffers
Note
Der Inhalt des Buffers ist nur solange vorhanden, wie IP-Symcon läuft. Mit einem Neustart verschwinden alle Informationen
Definition at line 358 of file IPSModule.php.
GetBufferList()
IPSModule::GetBufferList () protected
Diese Funktion liefert ein Array mit den Namen aller Buffer.
Returns
array Namensliste aller Buffer
Definition at line 350 of file IPSModule.php.
GetConfigurationForm()
IPSModule::GetConfigurationForm ()
Der Inhalt kann überschrieben werden um so eine selbsterstellte Konfigurationsseite zu übergeben. So können dynamisch Inhalte wiedergespiegelt werden. Die "form.json" auf dem Dateisystem wird dabei vollkommen ignoriert.
Returns
string Inhalt der Konfigurationsseite
Note
Wird diese Funktion nicht im eigenen Modul definiert, so wird standarmässig der Inhalt der form.json weitergegeben.
Definition at line 443 of file IPSModule.php.
GetConfigurationForParent()
IPSModule::GetConfigurationForParent ()
Der Konfiguration-String wird der übergeordeneten Instanz übergeben. Diese liest den String aus und setzt die eingetragenen Werte. Über diese Funktion eingelesene Werte können über die Konfigurationsseite nicht mehr verändert werden.
Returns
string Inhalt der Konfiguration der übergeordenten Instanz
Note
Wird diese Funktion nicht im eigenen Modul definiert, so wird standarmässig nichts verändert und die übergeordenete Instanz bleibt frei konfigurierbar.
Definition at line 450 of file IPSModule.php.
GetIDForIdent()
IPSModule::GetIDForIdent ($Ident) protected
Der Befehl sucht nach der ObjektID des Objekt mit dem Ident Ident und gibt diese zurück. Sollte der Ident nicht vorhanden sein, wird eine Fehlermeldung erzeugt.
Parameters
string $Ident Ident des Objekts nach dem gesucht werden soll.
Returns
bool|int ID des gefundenen Objekts, sonst FALSE
Definition at line 36 of file IPSModule.php.
Referenced by BaseRpcModule\CreateVarByIdent(), BaseRpcModule\GetDeviceState(), BaseRpcModule\GetValueByIdent(), BaseRpcModule\SetDeviceState(), BaseRpcModule\SetValueByIdent(), BaseRpcModule\UpdateDeviceProps(), and BaseRpcModule\ValidateConfiguration().
GetReferenceList()
IPSModule::GetReferenceList ()
Diese Funktion liefert ein Array mit den IDs aller Referenzen.
Returns
array Array mit Integer-Werten der IDs aller Referenzen
Definition at line 476 of file IPSModule.php.
MaintainAction()
IPSModule::MaintainAction ($Ident, $Action) protected
Die Funktion ruft bei AktionAktivieren == True die Funktion EnableAction und bei AktionAktivieren == False die Funktion DisableAction mit dem Ident Ident auf.
Parameters
string $Ident Ident der Variable
boolean $Action Enable wenn True, Disable wenn False
Definition at line 201 of file IPSModule.php.
MaintainVariable()
IPSModule::MaintainVariable ($Ident, $Name, $Type, $Profile, $Position, $Keep) protected
Wenn der Parameter Beibehalten == true ist, dann wird die Typ Typ passende Statusvariable mit dem Ident Ident und dem Namen Name erstellt. Wenn der Parameter Beibehalten == false ist, dann wird die Statusvariable mit dem Ident Ident gelöscht.
Parameters
string $Ident Ident der Statusvariable
string $Name Name der Statusvariable
integer $Type Typ der Statusvariable
string $Profile Name des Variablenprofils welches verwendet werden soll
integer $Position Postion im Objektbaum und somit auch im WebFront
boolean $Keep Register wenn True, Unregister wenn False
Note
Der Wert von Typ enthält den Variablentyp (0: Boolean, 1: Integer, 2: Float, 3: String). Siehe auch IPS_CreateVariable oder IPS_GetVariable
Definition at line 182 of file IPSModule.php.
MessageSink()
IPSModule::MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Der Inhalt der Funktion kann überschrieben werden um eigene Reaktionen auf bestimmte Nachrichten auszuführen. Die Funktion wird nur bei registrierten NachrichtenIDs/SenderIDs-Kombinationen aufgerufen. Der Zeitstempel wird für jede versendete Nachricht inkrementiert. RegisterMessage und UnregisterMessage fügt Filterregeln hinzu oder entfernt diese wieder.
Parameters
integer $TimeStamp Fortlaufender Zähler Zeitstempel
integer $SenderID ID des Senders
string $Message ID der Nachricht
array $Data Daten der Nachricht
Note
Wird diese Funktion nicht im eigenen Modul definiert, so wird die Standard MessageSink() ausgeführt.
Der Inhalt von Daten kann je nach Nachrichtentyp varieren. Diese sind noch undokumentiert.
Definition at line 392 of file IPSModule.php.
ReadAttributeBoolean()
IPSModule::ReadAttributeBoolean ($Name) protected
Die Funktion gibt den Wert des Attributs mit dem Namen Name zurück.
Parameters
string $Name Name des Attributs
Returns
boolean Der Wert des Attributs
Definition at line 237 of file IPSModule.php.
ReadAttributeFloat()
IPSModule::ReadAttributeFloat ($Name) protected
Die Funktion gibt den Wert des Attributs mit dem Namen Name zurück.
Parameters
string $Name Name des Attributs
Returns
float Der Wert des Attributs
Definition at line 251 of file IPSModule.php.
ReadAttributeInteger()
IPSModule::ReadAttributeInteger ($Name) protected
Die Funktion gibt den Wert des Attributs mit dem Namen Name zurück.
Parameters
string $Name Name des Attributs
Returns
integer Der Wert des Attributs
Definition at line 244 of file IPSModule.php.
ReadAttributeString()
IPSModule::ReadAttributeString ($Name) protected
Die Funktion gibt den Wert des Attributs mit dem Namen Name zurück.
Parameters
string $Name Name des Attributs
Returns
string Der Wert des Attributs
Definition at line 258 of file IPSModule.php.
ReadPropertyBoolean()
IPSModule::ReadPropertyBoolean ($Name) protected
Die Funktion gibt den Wert der Eigenschaft mit dem Namen Name zurück.
Parameters
string $Name Name der Eigenschaft
Returns
boolean Der Wert der Eigenschaft
Definition at line 209 of file IPSModule.php.
Referenced by BaseRpcModule\ValidateConfiguration().
ReadPropertyFloat()
IPSModule::ReadPropertyFloat ($Name) protected
Die Funktion gibt den Wert der Eigenschaft mit dem Namen Name zurück.
Parameters
string $Name Name der Eigenschaft
Returns
float Der Wert der Eigenschaft
Definition at line 223 of file IPSModule.php.
ReadPropertyInteger()
IPSModule::ReadPropertyInteger ($Name) protected
Die Funktion gibt den Wert der Eigenschaft mit dem Namen Name zurück.
Parameters
string $Name Name der Eigenschaft
Returns
integer Der Wert der Eigenschaft
Definition at line 216 of file IPSModule.php.
Referenced by BaseRpcModule\GetProps(), BaseRpcModule\StartTimer(), and BaseRpcModule\ValidateTimers().
ReadPropertyString()
IPSModule::ReadPropertyString ($Name) protected
Die Funktion gibt den Wert der Eigenschaft mit dem Namen Name zurück.
Parameters
string $Name Name der Eigenschaft
Returns
string Der Wert der Eigenschaft
Definition at line 230 of file IPSModule.php.
Referenced by IPSRpcModule\ApplyHost(), BaseRpcModule\CheckOnline(), IPSRpcModule\CreateApi(), IPSRpcModule\GetDeviceConfig(), IPSRpcModule\ReDiscover(), and BaseRpcModule\ValidateConfiguration().
ReceiveData()
IPSModule::ReceiveData ($JSONString)
Diese Funktion wird von IP-Symcon aufgerufen und verarbeitet zugesendete Daten und schickt diese gegenenfalls an alle untergeordneten Instanzen weiter. Daten können über die Funktion SendDataToChildren versendet werden. Weitere Informationen zur Datenweiterleitung können unter Datenfluss gefunden werden.
Parameters
string $JSONString Datenpaket im JSON Format
Note
Die ReceiveData Funktion wird von IP-Symcon aufgerufen. Sie muss somit von der Basisklasse überschrieben werden, um eigene Erweiterungen hinzuzufügen
Definition at line 413 of file IPSModule.php.
RegisterAttributeBoolean()
IPSModule::RegisterAttributeBoolean ($Name, $DefaultValue) protected
Diese Funktion erstellt ein Attribut vom Typ Boolean mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
boolean $DefaultValue Standardwert der Eigenschaft
Note
Diese Funktion kann ausschließlich in der Create Methode aufgerufen werden!
Definition at line 71 of file IPSModule.php.
RegisterAttributeFloat()
IPSModule::RegisterAttributeFloat ($Name, $DefaultValue) protected
Diese Funktion erstellt ein Attribut vom Typ Float mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
float $DefaultValue Standardwert der Eigenschaft
Note
Diese Funktion kann ausschließlich in der Create Methode aufgerufen werden!
Definition at line 87 of file IPSModule.php.
RegisterAttributeInteger()
IPSModule::RegisterAttributeInteger ($Name, $DefaultValue) protected
Diese Funktion erstellt ein Attribut vom Typ Integer mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
integer $DefaultValue Standardwert der Eigenschaft
Note
Diese Funktion kann ausschließlich in der Create Methode aufgerufen werden!
Definition at line 79 of file IPSModule.php.
RegisterAttributeString()
IPSModule::RegisterAttributeString ($Name, $DefaultValue) protected
Diese Funktion erstellt ein Attribut vom Typ String mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
string $DefaultValue Standardwert der Eigenschaft
Note
Diese Funktion kann ausschließlich in der Create Methode aufgerufen werden!
Definition at line 95 of file IPSModule.php.
RegisterMessage()
IPSModule::RegisterMessage ($SenderID, $Message) protected
Diese Funktion registriert das Modul für den Empfang der Nachricht NachrichtID und der ID SenderID.
Parameters
integer $SenderID ID des Senders
integer $Message ID der Nachricht
Note
Ein mehrfaches Aufrufen mit den selben Parametern registriert dennoch nur einmalig
Definition at line 374 of file IPSModule.php.
Referenced by BaseRpcModule\Create().
RegisterPropertyBoolean()
IPSModule::RegisterPropertyBoolean ($Name, $DefaultValue) protected
Diese Funktion erstellt eine Eigenschaft vom Typ Boolean mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
boolean $DefaultValue Standardwert der Eigenschaft
Definition at line 42 of file IPSModule.php.
Referenced by GenericRpc\Create(), and BaseRpcModule\Create().
RegisterPropertyFloat()
IPSModule::RegisterPropertyFloat ($Name, $DefaultValue) protected
Diese Funktion erstellt eine Eigenschaft vom Typ Float mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
float $DefaultValue Standardwert der Eigenschaft
Definition at line 56 of file IPSModule.php.
RegisterPropertyInteger()
IPSModule::RegisterPropertyInteger ($Name, $DefaultValue) protected
Diese Funktion erstellt eine Eigenschaft vom Typ Integer mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
integer $DefaultValue Standardwert der Eigenschaft
Definition at line 49 of file IPSModule.php.
Referenced by GenericRpc\Create(), and BaseRpcModule\Create().
RegisterPropertyString()
IPSModule::RegisterPropertyString ($Name, $DefaultValue) protected
Diese Funktion erstellt eine Eigenschaft vom Typ String mit dem Namen Name und dem Standardwert Standardwert
Parameters
string $Name Name der Eigenschaft
string $DefaultValue Standardwert der Eigenschaft
Definition at line 63 of file IPSModule.php.
Referenced by BaseRpcModule\Create(), and IPSRpcModule\Create().
RegisterReference()
IPSModule::RegisterReference (int $ID) protected
Diese Funktion registriert die ID ID als referenziert, sodass das Modul bei einer Referenzsuche gefunden wird.
Parameters
int $ID ID des Objekts
Note
Ein mehrfaches Aufrufen mit der selben ID registriert dennoch nur einmalig
Definition at line 464 of file IPSModule.php.
RegisterScript()
IPSModule::RegisterScript ($Ident, $Name, $Content, $Position) protected
Erstellt ein Skript mit dem Ident Ident, Namen Name, Inhalt Inhalt und der Position Postion, sofern der angegebene Ident nicht schon vorhanden ist. In beiden Fällen wird die ObjektID des erstellten oder bereits vorhanden Skripts zurückgegeben.
Parameters
string $Ident Ident des Skripts
string $Name Name des Skripts
string $Content Inhalt, welcher in das Skript eingetragen werden soll. Default == "<?\n\n//Autogenerated script\n\n?>"
integer $Position Position im Objektbaum und somit auch in der Visualisierung. Default == 0
Note
Der Inhalt von Inhalt wird jedes mal überschrieben, sodass auch nach Änderungen immer der korrekte Inhalt garantiert werden kann. Für Skripte welche bearbeitet werden sollen, ist es empfohlen ein Konfigurationsformular mit SelectScript-Auswahl zu nutzen
Definition at line 124 of file IPSModule.php.
RegisterTimer()
IPSModule::RegisterTimer ($Ident, $Milliseconds, $ScriptText) protected
Diese Funktion erstellt einen Timer mit dem Namen Name. Es kann noch angegeben werden, welches Intervall beim Erstellen gesetzt werden soll und der Skriptinhalt wird definiert. Der Timer ist stateless. Das heißt bei jedem Neustart wird der Timer mit dem hier eingestellten Intervall neuerstellt. Intervalleinstellungen müssen in der ApplyChanges() neu geladen werden.
Parameters
string $Ident Name des Timers
int $Milliseconds Intervall in Millisekunden mit dem der Timer erstellt werden soll. 0 = Niemals
string $ScriptText PHP Skript ohne PHP Tags (<? … ?>)
Returns
int InstanzID des erstellten Timers
Note
Der Timer kann nur in der "Create()"-Funktion erstellt werden. Soll der Timer ausgeschaltet werden oder nicht starten: SetTimerInterval auf 0 setzen.
Der Inhalt von Skriptinhalt wird jedes mal überschrieben, sodass auch nach Änderungen immer der korrekte Inhalt garantiert werden kann.
Definition at line 106 of file IPSModule.php.
Referenced by BaseRpcModule\Create().
RegisterVariableBoolean()
IPSModule::RegisterVariableBoolean ($Ident, $Name, $Profile, $Position) protected
Diese Funktion erstellt eine Statusvariable vom Typ Boolean mit dem Ident Ident dem Namen Name. Es kann noch angegeben werden, welches Profil genutzt werden und auf welcher Position die Statusvariable stehen soll.
Parameters
string $Ident Ident der Statusvariable
string $Name Name der Statusvariable
string $Profile Name des zu verwendenen Profils. Default == ""
integer $Position Position im Objektbaum und somit auch in der Visualisierung. Default == 0
Note
Über GetIDForIdent kann die VariablenID ermittelt werden, sodass diese nirgends gespeichert werden muss.
Definition at line 134 of file IPSModule.php.
Referenced by BaseRpcModule\CreateVarByIdent().
RegisterVariableFloat()
IPSModule::RegisterVariableFloat ($Ident, $Name, $Profile, $Position) protected
Diese Funktion erstellt eine Statusvariable vom Typ Float mit dem Ident Ident dem Namen Name. Es kann noch angegeben werden, welches Profil genutzt werden und auf welcher Position die Statusvariable stehen soll.
Parameters
string $Ident Ident der Statusvariable
string $Name Name der Statusvariable
string $Profile Name des zu verwendenen Profils. Default == ""
integer $Position Position im Objektbaum und somit auch in der Visualisierung. Default == 0
Note
Über GetIDForIdent kann die VariablenID ermittelt werden, sodass diese nirgends gespeichert werden muss.
Definition at line 154 of file IPSModule.php.
Referenced by BaseRpcModule\CreateVarByIdent().
RegisterVariableInteger()
IPSModule::RegisterVariableInteger ($Ident, $Name, $Profile, $Position) protected
Diese Funktion erstellt eine Statusvariable vom Typ Integer mit dem Ident Ident dem Namen Name. Es kann noch angegeben werden, welches Profil genutzt werden und auf welcher Position die Statusvariable stehen soll.
Parameters
string $Ident Ident der Statusvariable
string $Name Name der Statusvariable
string $Profile Name des zu verwendenen Profils. Default == ""
integer $Position Position im Objektbaum und somit auch in der Visualisierung. Default == 0
Note
Über GetIDForIdent kann die VariablenID ermittelt werden, sodass diese nirgends gespeichert werden muss.
Definition at line 144 of file IPSModule.php.
Referenced by BaseRpcModule\CreateVarByIdent(), BaseRpcModule\GetDeviceState(), BaseRpcModule\SetDeviceState(), and BaseRpcModule\ValidateConfiguration().
RegisterVariableString()
IPSModule::RegisterVariableString ($Ident, $Name, $Profile, $Position) protected
Diese Funktion erstellt eine Statusvariable vom Typ String mit dem Ident Ident dem Namen Name. Es kann noch angegeben werden, welches Profil genutzt werden und auf welcher Position die Statusvariable stehen soll.
Parameters
string $Ident Ident der Statusvariable
string $Name Name der Statusvariable
string $Profile Name des zu verwendenen Profils. Default == ""
integer $Position Position im Objektbaum und somit auch in der Visualisierung. Default == 0
Note
Über GetIDForIdent kann die VariablenID ermittelt werden, sodass diese nirgends gespeichert werden muss.
Definition at line 164 of file IPSModule.php.
Referenced by BaseRpcModule\CreateVarByIdent().
RequestAction()
IPSModule::RequestAction ($Ident, $Value)
Wird aufgerufen wenn in der Visualisierung auf z.B. eine Schaltfläche geklickt wird.
Parameters
string $Ident Ident der Variable
string $Value Der Wert, welcher gesetzt werden soll
Note
Die RequestAction Funktion wird von IP-Symcon aufgerufen. Sie muss somit von der Basisklasse überschrieben werden, um eigene Erweiterungen hinzuzufügen
Definition at line 436 of file IPSModule.php.
RequireParent()
IPSModule::RequireParent ($ModuleID) protected
Sofern keine Verbindung existiert, wird eine übergeordnete Instanz mit der GUID ÜbergordneteGUID erstellt. Selbst dann, wenn eine kompatible übergeordneten Instanz vorhanden wäre.
Parameters
string $ModuleID GUID der übergeordneten Instanz
Note
Der Normalfall für die Funktion ist ein Splitter-Modul, welches beim Erstellen eine eigene I/O Instanz benötigt. Alternativ ist eventuell auch ForceParent passend.
Diese Funktion wird normalerweise nur in der Create() oder ApplyChanges() Methode aufgerufen.
Definition at line 317 of file IPSModule.php.
SendDataToChildren()
IPSModule::SendDataToChildren ($Data) protected
Diese Funktion sendet Daten an alle verbundenen untergeordneten Instanzen. Weitere Informationen sind unter Datenfluss zu finden.
Parameters
string $Data JSON kodierter String
Definition at line 303 of file IPSModule.php.
SendDataToParent()
IPSModule::SendDataToParent ($Data) protected
Diese Funktion sendet Daten an eine verbundene übergeordnete Instanz. Weitere Informationen sind unter Datenfluss zu finden.
Parameters
string $Data JSON kodierter String
Returns
mixed Ergebnis, welches ForwardData von der übergeordneten Instanz liefert
Definition at line 297 of file IPSModule.php.
SendDebug()
IPSModule::SendDebug ($Message, $Data, $Format) protected
Gibt die Debugmeldung Daten unter dem Meldungsname Meldungsname und dem Format Format aus. Format gibt dabei an ob bei automatischer Darstellung entweder Text oder Hex Ausgabe ausgewählt wird.
Parameters
string $Message Name/Titel der Debugausgabe
string $Data Inhalt der Debugmeldung
integer $Format Voreinstellung für automatische Formationsauswahl (0 = Text, 1 = Hex)
Definition at line 366 of file IPSModule.php.
Referenced by BaseRpcModule\ApplyChanges(), IPSRpcModule\ApplyHost(), IPSRpcModule\CallApi(), IPSRpcModule\CreateApi(), BaseRpcModule\CreateVarByIdent(), IPSRpcModule\GetDeviceConfig(), IPSRpcModule\ReDiscover(), BaseRpcModule\SetProps(), and BaseRpcModule\ValidateTimers().
SetBuffer()
IPSModule::SetBuffer ($Name, $Data) protected
Diese Funktion schreibt Daten Data in den Buffer mit dem Namen Name.
Parameters
string $Name Name des Buffers
string $Data Daten welche in den Buffer gepackt werden sollen.
Note
Der Buffer besitzt ein Softlimt von 8kb und ein Hardlimit von 64kb. Das heißt ab 8kb größe wirft IP-Symcon eine "Warning" in die Meldungen und die maximale Größe des Buffers beträgt 64kb. Daten größer als 64kb werden abgeschnitten.
Der Inhalt des Buffers ist nur solange vorhanden, wie IP-Symcon läuft. Mit einem Neustart verschwinden alle Informationen.
Definition at line 344 of file IPSModule.php.
SetForwardDataFilter()
IPSModule::SetForwardDataFilter ($RequiredRegexMatch) protected
Setzt den Filter mit der Regular Expression ErforderlicheRegexRegel. ForwardData() wird nur aufgerufen wenn der gesetzte Filter zutrifft.
Parameters
string $RequiredRegexMatch Regexregel welche als Filter angewendet werden soll
Definition at line 419 of file IPSModule.php.
SetReceiveDataFilter()
IPSModule::SetReceiveDataFilter ($RequiredRegexMatch) protected
Setzt den Filter mit der Regular Expression ErforderlicheRegexRegel. RecieveData() wird nur aufgerufen wenn der gesetzte Filter zutrifft.
Parameters
string $RequiredRegexMatch Regexregel welche als Filter angewendet werden soll
Definition at line 404 of file IPSModule.php.
SetStatus()
IPSModule::SetStatus ($Status) protected
Setzt den Satus einer Instanz auf den Wert von Statuswert.
Parameters
integer $Status Der Statuswert auf den die Instanz gesetzt werden soll.
Definition at line 329 of file IPSModule.php.
SetSummary()
IPSModule::SetSummary ($Summary) protected
Diese Funktion setzt die Kurzinformation Kurzinfo des Objekts, welche in der Verwaltungskonsole angezeigt wird und durch IPS_GetObject wieder ausgelesen werden kann.
Parameters
string $Summary Inhalt der gesetzt werden soll
Definition at line 335 of file IPSModule.php.
SetTimerInterval()
IPSModule::SetTimerInterval ($Name, $Milliseconds) protected
Setzt den Intervall des Timers Name auf den Wert von Interval.
Parameters
string $Name Der Name des Timers dessen Intervall gesetzt werden soll.
integer $Milliseconds Der Intervall in Millisekunden auf den der Timer gesetzt werden soll.
Note
Wie in RegisterTimer beschrieben, ist der Timer stateless und bei einem Neustart vom IP-Symcon-Server muss der Timer neugesetzt werden, ansonsten nimmt er den Wert von RegisterTimer.
Definition at line 114 of file IPSModule.php.
Referenced by BaseRpcModule\StartTimer(), and BaseRpcModule\StopTimer().
Translate()
IPSModule::Translate ($Text)
Übersetzt den String Text anhand der ausgewählten Systemsprache und der locale.json.
Parameters
string $Text Zu übersetzender Text
Returns
string Übersetzter Text
Note
Wenn keine locale.json vorhanden ist oder der String nicht in der locale.json gefunden werden kann, wird der ursprüngliche Text zurückgegeben.
Definition at line 458 of file IPSModule.php.
Referenced by BaseRpcModule\Create(), MediaRpc\CreateMissedProfile(), BaseRpcModule\CreateVarByIdent(), GenericRpc\GetConfigurationForm(), BaseRpcModule\GetDeviceState(), BaseRpcModule\SetDeviceState(), and BaseRpcModule\ValidateConfiguration().
UnregisterMessage()
IPSModule::UnregisterMessage ($SenderID, $Message) protected
Diese Funktion entfernt eine Registrierung des Moduls für den Empfang der Nachricht NachrichtID und der ID SenderID.
Parameters
integer $SenderID ID des Senders
integer $Message ID der Nachricht
Definition at line 381 of file IPSModule.php.
UnregisterReference()
IPSModule::UnregisterReference (int $ID) protected
Diese Funktion entfernt die ID ID als referenziert für das Modul.
Parameters
int $ID ID des Objekts
Definition at line 470 of file IPSModule.php.
UnregisterVariable()
IPSModule::UnregisterVariable ($Ident) protected
Der Befehl löscht die Statusvariable mit dem Ident Ident
Parameters
string $Ident Ident der Statusvariable
Definition at line 170 of file IPSModule.php.
Referenced by BaseRpcModule\UpdateDeviceProps(), and BaseRpcModule\ValidateConfiguration().
WriteAttributeBoolean()
IPSModule::WriteAttributeBoolean ($Name, $Value) protected
Die Funktion schreibt den Wert Value in das Attribut mit dem Namen Name.
Parameters
string $Name Name des Attributs
boolean $Value Neuer Wert des Attributs
Note
Veränderte Werte sind im Vergleich zu Properties sofort verfügbar
Definition at line 266 of file IPSModule.php.
WriteAttributeFloat()
IPSModule::WriteAttributeFloat ($Name, $Value) protected
Die Funktion schreibt den Wert Value in das Attribut mit dem Namen Name.
Parameters
string $Name Name des Attributs
float $Value Neuer Wert des Attributs
Note
Veränderte Werte sind im Vergleich zu Properties sofort verfügbar
Definition at line 282 of file IPSModule.php.
WriteAttributeInteger()
IPSModule::WriteAttributeInteger ($Name, $Value) protected
Die Funktion schreibt den Wert Value in das Attribut mit dem Namen Name.
Parameters
string $Name Name des Attributs
integer $Value Neuer Wert des Attributs
Note
Veränderte Werte sind im Vergleich zu Properties sofort verfügbar
Definition at line 274 of file IPSModule.php.
WriteAttributeString()
IPSModule::WriteAttributeString ($Name, $Value) protected
Die Funktion schreibt den Wert Value in das Attribut mit dem Namen Name.
Parameters
string $Name Name des Attributs
string $Value Neuer Wert des Attributs
Note
Veränderte Werte sind im Vergleich zu Properties sofort verfügbar
Definition at line 290 of file IPSModule.php.
Member Data Documentation
$InstanceID
int IPSModule::$InstanceID protected
ID dieser Instanz
Definition at line 12 of file IPSModule.php.
Referenced by IPSRpcModule\RegisterHook().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/IPSModule.php