RpcTools 5.x Project: MediaRpc Class Reference
MediaRpc Class Reference
Public Member Functions
RequestAction ($Ident, $Value)
Destroy ()
WriteValue (string $Ident, string $Value)
RequestUpdate ()
Public Member Functions inherited from IPSRpcModule
Create ()
GetApi ()
GetApiInfo ()
Get current device api info.
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles for Device .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Member Functions inherited from IPSModule
__construct ($InstanceID)
Create ()
Destroy ()
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
ApplyChanges ()
ReceiveData ($JSONString)
ForwardData ($JSONString)
RequestAction ($Ident, $Value)
GetConfigurationForm ()
GetConfigurationForParent ()
Translate ($Text)
GetReferenceList ()
Public Attributes
PROP_MUTE_CONTROL =>'MUTE',PROP_TREBLE_CONTROL=>'TREBLE',PROP_BASS_CONTROL=>'BASS',PROP_LOUDNESS_CONTROL=>'LOUDNESS',PROP_BRIGHTNESS_CONTROL=>'BRIGHTNESS',PROP_CONTRAST_CONTROL=>'CONTRAST',PROP_SHARPNESS_CONTROL=>'SHARPNESS',PROP_COLOR_CONTROL=>'COLOR',PROP_SOURCE_CONTROL=>'SOURCE',PROP_PLAY_CONTROL=>'PLAYSTATE',PROP_CONTENT_BROWSER=>'CONTENT']
Protected Member Functions
GetDiscoverDeviceOptions ()
ApplyDeviceProps ($Props, $doApply)
DoUpdate ()
CreateMissedProfile ($name)
GetPropDef ($Ident)
Protected Member Functions inherited from IPSRpcModule
ApplyDeviceProps ($Props, $doApply)
DoUpdate ()
This function is called from RunUpdate and handle updates for status variables.
RunUpdate ()
GetDeviceConfig ()
Get config array to initilize RpcApi.
CreateApi ()
Return RpcApi object.
CallApi (string $function, array $arguments=[])
Make a rpc call.
GetDiscoverDeviceOptions ()
Get the default discover device config. Need to auto configure Device.
ApplyHost ($host, $doApply=true)
ReDiscover ()
RegisterHook ($Name, bool $Create)
Register a Hook for external calls.
ProcessHookData ()
Process the hook data.
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current configuration.
SetStatus ($Status)
Set module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
Get device state.
SetDeviceState ($State)
Set device state.
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the module propertys.
SetProps (int $props, $Update=true, $doApply=true)
Setup module propertys.
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
Update module status variables by propertys.
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Override in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
Get status variable value by ident.
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
Set status variable value by ident.
CreateVarByProp ($Prop)
Create status variable by module property.
CreateVarByIdent ($Ident, $CheckIdent=true)
Create status variable by ident.
ValidIdent ($Ident, $CheckProp=false)
Checks if ident valid.
CreateMissedProfile ($name)
Is called if a profile missed.
GetPropDef ($Ident)
Returns status variable definition.
GetModuleName ($name, $host)
Is called once if module created or Configuration valid.
IsLastInstance ($guid)
Checks if more instances created with then given module ID.
Protected Member Functions inherited from IPSModule
GetIDForIdent ($Ident)
RegisterPropertyBoolean ($Name, $DefaultValue)
RegisterPropertyInteger ($Name, $DefaultValue)
RegisterPropertyFloat ($Name, $DefaultValue)
RegisterPropertyString ($Name, $DefaultValue)
RegisterAttributeBoolean ($Name, $DefaultValue)
RegisterAttributeInteger ($Name, $DefaultValue)
RegisterAttributeFloat ($Name, $DefaultValue)
RegisterAttributeString ($Name, $DefaultValue)
RegisterTimer ($Ident, $Milliseconds, $ScriptText)
SetTimerInterval ($Name, $Milliseconds)
RegisterScript ($Ident, $Name, $Content, $Position)
RegisterVariableBoolean ($Ident, $Name, $Profile, $Position)
RegisterVariableInteger ($Ident, $Name, $Profile, $Position)
RegisterVariableFloat ($Ident, $Name, $Profile, $Position)
RegisterVariableString ($Ident, $Name, $Profile, $Position)
UnregisterVariable ($Ident)
MaintainVariable ($Ident, $Name, $Type, $Profile, $Position, $Keep)
EnableAction ($Ident)
DisableAction ($Ident)
MaintainAction ($Ident, $Action)
ReadPropertyBoolean ($Name)
ReadPropertyInteger ($Name)
ReadPropertyFloat ($Name)
ReadPropertyString ($Name)
ReadAttributeBoolean ($Name)
ReadAttributeInteger ($Name)
ReadAttributeFloat ($Name)
ReadAttributeString ($Name)
WriteAttributeBoolean ($Name, $Value)
WriteAttributeInteger ($Name, $Value)
WriteAttributeFloat ($Name, $Value)
WriteAttributeString ($Name, $Value)
SendDataToParent ($Data)
SendDataToChildren ($Data)
ConnectParent ($ModuleID)
RequireParent ($ModuleID)
ForceParent ($ModuleID)
SetStatus ($Status)
SetSummary ($Summary)
SetBuffer ($Name, $Data)
GetBufferList ()
GetBuffer ($Name)
SendDebug ($Message, $Data, $Format)
RegisterMessage ($SenderID, $Message)
UnregisterMessage ($SenderID, $Message)
SetReceiveDataFilter ($RequiredRegexMatch)
SetForwardDataFilter ($RequiredRegexMatch)
RegisterReference (int $ID)
UnregisterReference (int $ID)
Protected Attributes
$timerDef =['ONLINE_INTERVAL'=>[10,'s']
$showRefreshButton =true
$prop_names = [PROP_VOLUME_CONTROL=>'VOLUME'
Protected Attributes inherited from IPSRpcModule
$showLogin =[true,true]
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Override this to configure Timers for Module.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable.
$online =null
if not checked then $online=null, true if online false if host not reachable
$state =null
State cache if not checked then $state=null, 0=connected | 1=disconnected | 2=error.
$status = null
Status cache if not checked then $status=null.
$prop_names = []
Contains a List of valid Propertys.
Protected Attributes inherited from IPSModule
$InstanceID
Private Member Functions
_readValue (string $Ident)
_writeValue (string $Ident, string $Value)
Detailed Description
Definition at line 4 of file module.php.
Member Function Documentation
_readValue()
MediaRpc::_readValue (string $Ident) private
Definition at line 123 of file module.php.
References IPSRpcModule\CallApi(), IPSRpcModule\CreateApi(), and BaseRpcModule\SetValueByIdent().
Referenced by DoUpdate().
_writeValue()
MediaRpc::_writeValue (string $Ident, string $Value) private
Definition at line 142 of file module.php.
References IPSRpcModule\CallApi(), IPSRpcModule\CreateApi(), and BaseRpcModule\SetValueByIdent().
Referenced by WriteValue().
ApplyDeviceProps()
MediaRpc::ApplyDeviceProps ($Props, $doApply) protected
See also
IPSRpcModule::ApplyDeviceProps()
Definition at line 60 of file module.php.
References BaseRpcModule\SetProps().
CreateMissedProfile()
MediaRpc::CreateMissedProfile ($name) protected
See also
BaseRpcModule::CreateMissedProfile()
Definition at line 79 of file module.php.
References UTILS\RegisterProfileInteger(), UTILS\RegisterProfileIntegerEx(), and IPSModule\Translate().
Destroy()
MediaRpc::Destroy ()
See also
BaseRpcModule::Destroy()
Definition at line 17 of file module.php.
References BaseRpcModule\IsLastInstance().
DoUpdate()
MediaRpc::DoUpdate () protected
See also
IPSRpcModule::DoUpdate()
Definition at line 67 of file module.php.
References _readValue(), and BaseRpcModule\GetProps().
GetDiscoverDeviceOptions()
MediaRpc::GetDiscoverDeviceOptions () protected
See also
IPSRpcModule::GetDiscoverDeviceOptions()
Definition at line 53 of file module.php.
References OPT_MINIMIZED, and OPT_PROPS_ONLY.
GetPropDef()
MediaRpc::GetPropDef ($Ident) protected
See also
BaseRpcModule::GetPropDef()
Definition at line 99 of file module.php.
References PROP_BASS_CONTROL, PROP_BRIGHTNESS_CONTROL, PROP_COLOR_CONTROL, PROP_CONTRAST_CONTROL, PROP_LOUDNESS_CONTROL, PROP_MUTE_CONTROL, PROP_PLAY_CONTROL, PROP_SHARPNESS_CONTROL, PROP_SOURCE_CONTROL, PROP_TREBLE_CONTROL, and PROP_VOLUME_CONTROL.
RequestAction()
MediaRpc::RequestAction ($Ident, $Value)
See also
BaseRpcModule::RequestAction()
Definition at line 9 of file module.php.
References WriteValue().
RequestUpdate()
MediaRpc::RequestUpdate ()
Definition at line 41 of file module.php.
References IPSRpcModule\RunUpdate().
WriteValue()
MediaRpc::WriteValue (string $Ident, string $Value)
Parameters
string $Ident
string $Value
Returns
void|NULL
Definition at line 29 of file module.php.
References _writeValue(), BaseRpcModule\CheckOnline(), BaseRpcModule\GetDeviceState(), BaseRpcModule\StartTimer(), BaseRpcModule\StopTimer(), and BaseRpcModule\ValidIdent().
Referenced by RequestAction().
Member Data Documentation
$prop_names
array MediaRpc::$prop_names = [PROP_VOLUME_CONTROL=>'VOLUME' protected
See also
BaseRpcModule::$prop_names
Definition at line 120 of file module.php.
$showRefreshButton
MediaRpc::$showRefreshButton =true protected
Definition at line 47 of file module.php.
$timerDef
MediaRpc::$timerDef =['ONLINE_INTERVAL'=>[10,'s'] protected
Definition at line 46 of file module.php.
PROP_MUTE_CONTROL
MediaRpc::PROP_MUTE_CONTROL =>'MUTE',PROP_TREBLE_CONTROL=>'TREBLE',PROP_BASS_CONTROL=>'BASS',PROP_LOUDNESS_CONTROL=>'LOUDNESS',PROP_BRIGHTNESS_CONTROL=>'BRIGHTNESS',PROP_CONTRAST_CONTROL=>'CONTRAST',PROP_SHARPNESS_CONTROL=>'SHARPNESS',PROP_COLOR_CONTROL=>'COLOR',PROP_SOURCE_CONTROL=>'SOURCE',PROP_PLAY_CONTROL=>'PLAYSTATE',PROP_CONTENT_BROWSER=>'CONTENT']
Definition at line 120 of file module.php.
Referenced by GetPropDef().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/MediaRpc/module.php