RpcTools 5.x Project: FritzHomeAuto Class Reference
FritzHomeAuto Class Reference
Public Member Functions
Create ()
Destroy ()
GetConfigurationForm ()
RequestAction ($Ident, $Value)
RequestUpdate ()
Public Member Functions inherited from IPSRpcModule
Create ()
GetApi ()
GetApiInfo ()
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance of RpcTools .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Attributes
PROP_TEMP =>'TEMP',PROP_IST=>'IST',PROP_SOLL=>'SOLL',PROP_REDUCED=>'REDUCED',PROP_COMFORT=>'COMFORT',PROP_APOWER=>'APOWER',PROP_TPOWER=>'TPOWER']
Protected Member Functions
ValidateConfiguration ()
GetDiscoverDeviceOptions ()
GetModuleName ($name, $host)
DoUpdate ()
CreateMissedProfile ($name)
GetPropDef ($Ident)
Protected Member Functions inherited from IPSRpcModule
DoUpdate ()
RunUpdate ()
StartTimer ($delay=0)
GetDeviceConfig ()
CreateApi ()
CallApi (string $function, array $arguments=[])
GetDiscoverDeviceOptions ()
ApplyHost ($host, $doApply=true)
ReDiscover ()
ApplyDeviceProps ($Props)
GetProps ()
SetProps (int $props, $Update=true, $doApply=true)
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
RegisterHook ($Name, bool $Create)
ProcessHookData ()
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current Configuration.
SetStatus ($Status)
Set Module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
SetDeviceState ($State)
CheckOnline ()
Checks if host online and setup devicestate.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
CreateVarByProp ($Prop)
CreateVarByIdent ($Ident, $CheckIdent=true)
ValidIdent ($Ident, $CheckProp=false)
CreateMissedProfile ($name)
GetPropDef ($Ident)
Returns variable definitions Must overide in your own Module.
GetProps ()
Get the device propertys.
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Overide in your own Module.
GetModuleName ($name, $host)
IsLastInstance ($guid)
Protected Attributes
$timerDef =['ONLINE_INTERVAL'=>[5,'m']
$requireLogin =[true,true]
$showRefreshButton =true
$prop_names = [PROP_SWITCH=>'SWITCH'
Protected Attributes inherited from IPSRpcModule
$showLogin =[true,true]
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Overide this to configure Timers for Module ONLINE_INTERVAL checks when device is Online OFFLINE_INTERVAL checks when device is offline Parameters for Checks are [0,'s'] first are the minimum value 0 = timer disabled second are the multiplicator s = seconds, m = minutes and h are hours.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable
$online =null
if not checked Null, true if online false if host not reachable
$state =null
State cache 0=connected | 1=disconnected | 2=error.
$status = null
Status cache
$prop_names = []
Contains a List of valid Propertys Key = Property value Value = Property ident name.
Private Member Functions
DoSwitch ($Value)
BuildDeviceAINOptionsBuffer ()
updateData ($doApply)
Detailed Description
Author
Xavier
Definition at line 8 of file module.php.
Member Function Documentation
BuildDeviceAINOptionsBuffer()
FritzHomeAuto::BuildDeviceAINOptionsBuffer () private
Definition at line 150 of file module.php.
References IPSRpcModule\CallApi().
Referenced by ValidateConfiguration().
Create()
FritzHomeAuto::Create ()
See also
IPSRpcModule::Create()
Definition at line 13 of file module.php.
CreateMissedProfile()
FritzHomeAuto::CreateMissedProfile ($name) protected
See also
BaseRpcModule::CreateMissedProfile()
Definition at line 114 of file module.php.
References UTILS\RegisterProfileFloat().
Destroy()
FritzHomeAuto::Destroy ()
See also
BaseRpcModule::Destroy()
Definition at line 23 of file module.php.
References BaseRpcModule\IsLastInstance().
DoSwitch()
FritzHomeAuto::DoSwitch ($Value) private
Definition at line 143 of file module.php.
References IPSRpcModule\CallApi(), BaseRpcModule\CheckOnline(), BaseRpcModule\GetDeviceState(), and BaseRpcModule\SetValueByIdent().
Referenced by RequestAction().
DoUpdate()
FritzHomeAuto::DoUpdate () protected
See also
IPSRpcModule::DoUpdate()
Definition at line 105 of file module.php.
References updateData().
GetConfigurationForm()
FritzHomeAuto::GetConfigurationForm ()
See also
BaseRpcModule::GetConfigurationForm()
Definition at line 33 of file module.php.
GetDiscoverDeviceOptions()
FritzHomeAuto::GetDiscoverDeviceOptions () protected
See also
IPSRpcModule::GetDiscoverDeviceOptions()
Definition at line 90 of file module.php.
References OPT_MINIMIZED, and OPT_SMALCONFIG.
GetModuleName()
FritzHomeAuto::GetModuleName ($name, $host) protected
See also
BaseRpcModule::GetModuleName()
Definition at line 98 of file module.php.
GetPropDef()
FritzHomeAuto::GetPropDef ($Ident) protected
See also
BaseRpcModule::GetPropDef()
Definition at line 124 of file module.php.
References PROP_APOWER, PROP_COMFORT, PROP_IST, PROP_REDUCED, PROP_SOLL, PROP_SWITCH, PROP_TEMP, and PROP_TPOWER.
RequestAction()
FritzHomeAuto::RequestAction ($Ident, $Value)
See also
BaseRpcModule::RequestAction()
Definition at line 48 of file module.php.
References DoSwitch().
RequestUpdate()
FritzHomeAuto::RequestUpdate ()
Definition at line 57 of file module.php.
References IPSRpcModule\RunUpdate().
updateData()
FritzHomeAuto::updateData ($doApply) private
IPS_HasChanges($this->InstanceID);
Definition at line 157 of file module.php.
References BaseRpcModule\$status, IPSRpcModule\CallApi(), PROP_APOWER, PROP_COMFORT, PROP_IST, PROP_REDUCED, PROP_SOLL, PROP_SWITCH, PROP_TEMP, PROP_TPOWER, IPSRpcModule\SetProps(), and BaseRpcModule\SetValueByIdent().
Referenced by DoUpdate(), and ValidateConfiguration().
ValidateConfiguration()
FritzHomeAuto::ValidateConfiguration () protected
See also
BaseRpcModule::ValidateConfiguration()
Definition at line 69 of file module.php.
References BuildDeviceAINOptionsBuffer(), PROP_SWITCH, BaseRpcModule\SetStatus(), and updateData().
Member Data Documentation
$prop_names
array FritzHomeAuto::$prop_names = [PROP_SWITCH=>'SWITCH' protected
See also
BaseRpcModule::$prop_names
Definition at line 141 of file module.php.
$requireLogin
FritzHomeAuto::$requireLogin =[true,true] protected
Definition at line 62 of file module.php.
$showRefreshButton
FritzHomeAuto::$showRefreshButton =true protected
Definition at line 63 of file module.php.
$timerDef
FritzHomeAuto::$timerDef =['ONLINE_INTERVAL'=>[5,'m'] protected
Definition at line 61 of file module.php.
PROP_TEMP
FritzHomeAuto::PROP_TEMP =>'TEMP',PROP_IST=>'IST',PROP_SOLL=>'SOLL',PROP_REDUCED=>'REDUCED',PROP_COMFORT=>'COMFORT',PROP_APOWER=>'APOWER',PROP_TPOWER=>'TPOWER']
Definition at line 141 of file module.php.
Referenced by GetPropDef(), and updateData().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/FritzHomeAuto/module.php