RpcTools 5.x Project: IPSRpcModule Class Reference
IPSRpcModule Class Reference
Public Member Functions
Create ()
GetApi ()
GetApiInfo ()
Get current device api info.
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles for Device .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Member Functions inherited from IPSModule
__construct ($InstanceID)
Create ()
Destroy ()
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
ApplyChanges ()
ReceiveData ($JSONString)
ForwardData ($JSONString)
RequestAction ($Ident, $Value)
GetConfigurationForm ()
GetConfigurationForParent ()
Translate ($Text)
GetReferenceList ()
Protected Member Functions
ApplyDeviceProps ($Props, $doApply)
DoUpdate ()
This function is called from RunUpdate and handle updates for status variables.
RunUpdate ()
GetDeviceConfig ()
Get config array to initilize RpcApi.
CreateApi ()
Return RpcApi object.
CallApi (string $function, array $arguments=[])
Make a rpc call.
GetDiscoverDeviceOptions ()
Get the default discover device config. Need to auto configure Device.
ApplyHost ($host, $doApply=true)
ReDiscover ()
RegisterHook ($Name, bool $Create)
Register a Hook for external calls.
ProcessHookData ()
Process the hook data.
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current configuration.
SetStatus ($Status)
Set module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
Get device state.
SetDeviceState ($State)
Set device state.
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the module propertys.
SetProps (int $props, $Update=true, $doApply=true)
Setup module propertys.
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
Update module status variables by propertys.
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Override in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
Get status variable value by ident.
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
Set status variable value by ident.
CreateVarByProp ($Prop)
Create status variable by module property.
CreateVarByIdent ($Ident, $CheckIdent=true)
Create status variable by ident.
ValidIdent ($Ident, $CheckProp=false)
Checks if ident valid.
CreateMissedProfile ($name)
Is called if a profile missed.
GetPropDef ($Ident)
Returns status variable definition.
GetModuleName ($name, $host)
Is called once if module created or Configuration valid.
IsLastInstance ($guid)
Checks if more instances created with then given module ID.
Protected Member Functions inherited from IPSModule
GetIDForIdent ($Ident)
RegisterPropertyBoolean ($Name, $DefaultValue)
RegisterPropertyInteger ($Name, $DefaultValue)
RegisterPropertyFloat ($Name, $DefaultValue)
RegisterPropertyString ($Name, $DefaultValue)
RegisterAttributeBoolean ($Name, $DefaultValue)
RegisterAttributeInteger ($Name, $DefaultValue)
RegisterAttributeFloat ($Name, $DefaultValue)
RegisterAttributeString ($Name, $DefaultValue)
RegisterTimer ($Ident, $Milliseconds, $ScriptText)
SetTimerInterval ($Name, $Milliseconds)
RegisterScript ($Ident, $Name, $Content, $Position)
RegisterVariableBoolean ($Ident, $Name, $Profile, $Position)
RegisterVariableInteger ($Ident, $Name, $Profile, $Position)
RegisterVariableFloat ($Ident, $Name, $Profile, $Position)
RegisterVariableString ($Ident, $Name, $Profile, $Position)
UnregisterVariable ($Ident)
MaintainVariable ($Ident, $Name, $Type, $Profile, $Position, $Keep)
EnableAction ($Ident)
DisableAction ($Ident)
MaintainAction ($Ident, $Action)
ReadPropertyBoolean ($Name)
ReadPropertyInteger ($Name)
ReadPropertyFloat ($Name)
ReadPropertyString ($Name)
ReadAttributeBoolean ($Name)
ReadAttributeInteger ($Name)
ReadAttributeFloat ($Name)
ReadAttributeString ($Name)
WriteAttributeBoolean ($Name, $Value)
WriteAttributeInteger ($Name, $Value)
WriteAttributeFloat ($Name, $Value)
WriteAttributeString ($Name, $Value)
SendDataToParent ($Data)
SendDataToChildren ($Data)
ConnectParent ($ModuleID)
RequireParent ($ModuleID)
ForceParent ($ModuleID)
SetStatus ($Status)
SetSummary ($Summary)
SetBuffer ($Name, $Data)
GetBufferList ()
GetBuffer ($Name)
SendDebug ($Message, $Data, $Format)
RegisterMessage ($SenderID, $Message)
UnregisterMessage ($SenderID, $Message)
SetReceiveDataFilter ($RequiredRegexMatch)
SetForwardDataFilter ($RequiredRegexMatch)
RegisterReference (int $ID)
UnregisterReference (int $ID)
Protected Attributes
$showLogin =[true,true]
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Override this to configure Timers for Module.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable.
$online =null
if not checked then $online=null, true if online false if host not reachable
$state =null
State cache if not checked then $state=null, 0=connected | 1=disconnected | 2=error.
$status = null
Status cache if not checked then $status=null.
$prop_names = []
Contains a List of valid Propertys.
Protected Attributes inherited from IPSModule
$InstanceID
Detailed Description
Author
Xavier
Definition at line 498 of file rpc_module.inc.
Member Function Documentation
ApplyDeviceProps()
IPSRpcModule::ApplyDeviceProps ($Props, $doApply) protected
Parameters
int $Props
bool $doApply
Note
Override in your own Module
Definition at line 551 of file rpc_module.inc.
Referenced by ApplyHost().
ApplyHost()
IPSRpcModule::ApplyHost ($host, $doApply = true) protected
See also
BaseRpcModule::ApplyHost()
Definition at line 644 of file rpc_module.inc.
References ApplyDeviceProps(), D_HOST, D_INFO, D_NAME, D_PROPS, DiscoverDevice(), DiscoverSaveDevice(), GetDiscoverDeviceOptions(), BaseRpcModule\GetModuleName(), MAX_CFG_SIZE_BEFORE_SAVE_AS_FILE, IPSModule\ReadPropertyString(), IPSModule\SendDebug(), and BaseRpcModule\SetStatus().
Referenced by ReDiscover().
CallApi()
IPSRpcModule::CallApi (string $function, array $arguments = []) protected
Make a rpc call.
Parameters
string $function Function name to call
array $arguments Function arguments
Returns
NULL|mixed Result of api call
Definition at line 624 of file rpc_module.inc.
References $api, CreateApi(), and IPSModule\SendDebug().
Referenced by MediaRpc\_readValue(), MediaRpc\_writeValue(), and GenericRpc\CallMethod().
Create()
IPSRpcModule::Create ()
See also
BaseRpcModule::Create()
Definition at line 503 of file rpc_module.inc.
References IPSModule\RegisterPropertyString().
CreateApi()
IPSRpcModule::CreateApi () protected
Return RpcApi object.
Returns
NULL|RpcApi Api object
Definition at line 591 of file rpc_module.inc.
References $api, BaseRpcModule\CheckOnline(), D_OPTIONS, GetDeviceConfig(), BaseRpcModule\GetDeviceState(), OPT_REQUIRE_LOGIN, IPSModule\ReadPropertyString(), IPSModule\SendDebug(), and BaseRpcModule\SetStatus().
Referenced by MediaRpc\_readValue(), MediaRpc\_writeValue(), CallApi(), GetApi(), and GetApiInfo().
DoUpdate()
IPSRpcModule::DoUpdate () abstract protected
This function is called from RunUpdate and handle updates for status variables.
Note
Override in your own Module
Referenced by RunUpdate().
GetApi()
IPSRpcModule::GetApi ()
Returns
NULL|RpcApi Returns api Object for complex calls outside Module
Definition at line 511 of file rpc_module.inc.
References $api, and CreateApi().
GetApiInfo()
IPSRpcModule::GetApiInfo ()
Get current device api info.
Returns
NULL|array Api Informations
Definition at line 525 of file rpc_module.inc.
References $api, and CreateApi().
GetDeviceConfig()
IPSRpcModule::GetDeviceConfig () protected
Get config array to initilize RpcApi.
Returns
NULL|array Api config
Definition at line 571 of file rpc_module.inc.
References IPSModule\ReadPropertyString(), and IPSModule\SendDebug().
Referenced by CreateApi(), GenericRpc\GetConfigurationForm(), and ReDiscover().
GetDiscoverDeviceOptions()
IPSRpcModule::GetDiscoverDeviceOptions () protected
Get the default discover device config. Need to auto configure Device.
Returns
array Discover config [int options, array filter=[], string init page='']
Note
Override in your own Module
Definition at line 636 of file rpc_module.inc.
References OPT_MINIMIZED, and OPT_PROPS_ONLY.
Referenced by ApplyHost().
ProcessHookData()
IPSRpcModule::ProcessHookData () protected
Process the hook data.
Returns
bool True if proceed successful
Definition at line 764 of file rpc_module.inc.
ReDiscover()
IPSRpcModule::ReDiscover () protected
Returns
void
Definition at line 707 of file rpc_module.inc.
References ApplyHost(), D_URLS, GetDeviceConfig(), IPSModule\ReadPropertyString(), and IPSModule\SendDebug().
RegisterHook()
IPSRpcModule::RegisterHook ($Name, bool $Create) protected
Register a Hook for external calls.
Parameters
string $Name Name of the hook
bool $Create if true Hook creating , if false delete hook
Returns
string|bool if creating then returns full hook name or false if error or nothing change
Definition at line 727 of file rpc_module.inc.
References IPSModule\$InstanceID.
RunUpdate()
IPSRpcModule::RunUpdate () protected
See also
BaseRpcModule::RunUpdate()
Definition at line 561 of file rpc_module.inc.
References BaseRpcModule\CheckOnline(), DoUpdate(), BaseRpcModule\GetDeviceState(), BaseRpcModule\StartTimer(), and BaseRpcModule\StopTimer().
Referenced by MediaRpc\RequestUpdate().
Member Data Documentation
$api
RpcApi IPSRpcModule::$api =null protected
Current rpc api object.
Definition at line 539 of file rpc_module.inc.
Referenced by CallApi(), CreateApi(), GetApi(), and GetApiInfo().
$lastError
string IPSRpcModule::$lastError ='' protected
Contains the last error of api call.
Definition at line 544 of file rpc_module.inc.
$showLogin
array IPSRpcModule::$showLogin =[true,true] protected
See also
BaseRpcModule::$showLogin
Definition at line 534 of file rpc_module.inc.
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/libs/rpc_module.inc