RpcTools 5.x Project: C:/IP-Symcon/modules/RpcTools/libs/discover.inc File Reference
discover.inc File Reference
Classes
class Cache
Functions
const DiscoverNetwork ($timeout=5, $retrys=1, $bind_to_my_ip='', $SenderID=0)
DiscoverCleanUpCache ()
Cleanup the Discover Cache.
DiscoverDevice ($urls, $options=1, $filter=[])
DiscoverSaveDevice ($device, $override=true, $filename='')
DiscoverDeleteDevice ($device, $filename='')
Variables
if(!defined('RPCTOOLS')) define('RPCTOOLS' __DIR__
const PropFunctions =[PROP_VOLUME_CONTROL=>['GetVolume','SetVolume']
const PROP_MUTE_CONTROL =>['GetMute'
const PROP_TREBLE_CONTROL =>['GetTreble'
const PROP_BASS_CONTROL =>['GetBass'
const PROP_LOUDNESS_CONTROL =>['GetLoudness'
const PROP_BRIGHTNESS_CONTROL =>['GetBrightness'
const PROP_CONTRAST_CONTROL =>['GetContrast'
const PROP_SHARPNESS_CONTROL =>['GetSharpness'
const PROP_COLOR_CONTROL =>['GetColor'
const PROP_SOURCE_CONTROL =>['GetSource'
const PROP_PLAY_CONTROL =>['Stop'
const PROP_CONTENT_BROWSER =>['Browse'
Function Documentation
DiscoverCleanUpCache()
DiscoverCleanUpCache ()
Cleanup the Discover Cache.
Definition at line 75 of file discover.inc.
DiscoverDeleteDevice()
DiscoverDeleteDevice ($device, $filename = '')
Parameters
array $device
string $filename
Definition at line 350 of file discover.inc.
References D_NAME.
DiscoverDevice()
DiscoverDevice ($urls, $options = 1, $filter = [])
Parameters
string | array $urls
number $options
array $filter
Returns
array
Definition at line 85 of file discover.inc.
References D_HOST, D_INFO, D_NAME, D_OPTIONS, D_PROPS, D_SERVICES, D_TYPE, D_URLS, DiscoverSaveDevice(), ID_VARTABLE, OPT_EVENTS, OPT_MINIMIZED, OPT_PROPS_ONLY, OPT_REQUIRE_LOGIN, OPT_SAVECONVIG, OPT_SMALCONFIG, OPT_USE_CACHE, PROP_EVENTS, PropFunctions, S_CON, S_CURL, S_EURL, S_EVENTS, S_FUNCS, S_LOWERNAMES, S_PORT, S_URN, V_ALLOWED, V_DEFAULT, V_MAX, V_MIN, V_STEP, and V_TYPE.
Referenced by IPSRpcModule\ApplyHost().
DiscoverNetwork()
const DiscoverNetwork ($timeout = 5, $retrys = 1, $bind_to_my_ip = '', $SenderID = 0)
Parameters
number $timeout
number $retrys
string $bind_to_my_ip
number $SenderID
Returns
array|null
Definition at line 18 of file discover.inc.
DiscoverSaveDevice()
DiscoverSaveDevice ($device, $override = true, $filename = '')
Parameters
array $device
boolean $override
string $filename
Returns
string The Filename of saved Device
Definition at line 339 of file discover.inc.
References D_NAME.
Referenced by IPSRpcModule\ApplyHost(), and DiscoverDevice().
Variable Documentation
__DIR__
if (!defined('RPCTOOLS')) define('RPCTOOLS' __DIR__
Definition at line 2 of file discover.inc.
PROP_BASS_CONTROL
const PROP_BASS_CONTROL =>['GetBass'
Definition at line 7 of file discover.inc.
PROP_BRIGHTNESS_CONTROL
const PROP_BRIGHTNESS_CONTROL =>['GetBrightness'
Definition at line 7 of file discover.inc.
PROP_COLOR_CONTROL
const PROP_COLOR_CONTROL =>['GetColor'
Definition at line 7 of file discover.inc.
PROP_CONTENT_BROWSER
const PROP_CONTENT_BROWSER =>['Browse'
Definition at line 7 of file discover.inc.
PROP_CONTRAST_CONTROL
const PROP_CONTRAST_CONTROL =>['GetContrast'
Definition at line 7 of file discover.inc.
PROP_LOUDNESS_CONTROL
const PROP_LOUDNESS_CONTROL =>['GetLoudness'
Definition at line 7 of file discover.inc.
PROP_MUTE_CONTROL
const PROP_MUTE_CONTROL =>['GetMute'
Definition at line 7 of file discover.inc.
PROP_PLAY_CONTROL
const PROP_PLAY_CONTROL =>['Stop'
Definition at line 7 of file discover.inc.
PROP_SHARPNESS_CONTROL
const PROP_SHARPNESS_CONTROL =>['GetSharpness'
Definition at line 7 of file discover.inc.
PROP_SOURCE_CONTROL
const PROP_SOURCE_CONTROL =>['GetSource'
Definition at line 7 of file discover.inc.
PROP_TREBLE_CONTROL
const PROP_TREBLE_CONTROL =>['GetTreble'
Definition at line 7 of file discover.inc.
PropFunctions
const PropFunctions =[PROP_VOLUME_CONTROL=>['GetVolume','SetVolume']
Definition at line 7 of file discover.inc.
Referenced by DiscoverDevice().