RpcTools 5.x Project: RpcApi Class Reference
RpcApi Class Reference
Public Member Functions
__construct ($device_cfg, $host='', $user='', $pass='')
__call ($fn, $args)
__get ($n)
__set ($n, $v)
SetErrorHandler ($func)
LastError ()
FunctionExists ($name, $serviceName='')
Check if function is valid.
FunctionList ($a1=true, $a2=true)
DeviceInfo ()
Protected Member Functions
getDefaultValue ($name, $serviceName)
Private Member Functions
error ($msg, $code=E_USER_ERROR)
_validateFunctionName (&$name, &$serviceName)
_prepareArguments (&$arguments, $func_keys, $sn='')
_getFunctionParam ($name, $serviceName='')
_callInternal ($function, $arguments, $serviceName)
_callSoap ($function, $arguments, $serviceName)
_callUrl ($function, $arguments, $serviceName)
_callRpc ($function, array $arguments, string $serviceName, bool $AsXmlrpc=false)
Private Attributes
$device =null
$user =''
$pass =''
$ErrorHandler =null
$lastError =''
$UserVars = []
Detailed Description
Definition at line 6 of file rpc_api.inc.
Constructor & Destructor Documentation
__construct()
RpcApi::__construct ($device_cfg, $host = '', $user = '', $pass = '')
Definition at line 19 of file rpc_api.inc.
References $pass, $user, and D_HOST.
Member Function Documentation
__call()
RpcApi::__call ($fn, $args)
Definition at line 38 of file rpc_api.inc.
References _callInternal(), _callRpc(), _callSoap(), _callUrl(), _validateFunctionName(), D_HOST, D_SERVICES, error(), and S_CON.
__get()
RpcApi::__get ($n)
Definition at line 66 of file rpc_api.inc.
References D_HOST, D_INFO, D_NAME, D_PROPS, D_SERVICES, D_URLS, and S_PORT.
__set()
RpcApi::__set ($n, $v)
Definition at line 81 of file rpc_api.inc.
_callInternal()
RpcApi::_callInternal ($function, $arguments, $serviceName) private
Definition at line 217 of file rpc_api.inc.
References _getFunctionParam(), and V_ALLOWED.
Referenced by __call().
_callRpc()
RpcApi::_callRpc ($function, array $arguments, string $serviceName, bool $AsXmlrpc = false) private
Definition at line 292 of file rpc_api.inc.
References D_HOST, D_SERVICES, error(), S_CURL, S_PORT, xmlrpc_decode(), and xmlrpc_encode_request().
Referenced by __call().
_callSoap()
RpcApi::_callSoap ($function, $arguments, $serviceName) private
Definition at line 251 of file rpc_api.inc.
References $pass, $user, _prepareArguments(), D_HOST, D_SERVICES, error(), S_CURL, S_FUNCS, S_PORT, and S_URN.
Referenced by __call().
_callUrl()
RpcApi::_callUrl ($function, $arguments, $serviceName) private
Definition at line 267 of file rpc_api.inc.
References _prepareArguments(), D_HOST, D_SERVICES, error(), S_CURL, S_FUNCS, S_LOWERNAMES, and S_PORT.
Referenced by __call().
_getFunctionParam()
RpcApi::_getFunctionParam ($name, $serviceName = '') private
Definition at line 205 of file rpc_api.inc.
References D_SERVICES, and ID_VARTABLE.
Referenced by _callInternal(), and getDefaultValue().
_prepareArguments()
RpcApi::_prepareArguments (& $arguments, $func_keys, $sn = '') private
Definition at line 192 of file rpc_api.inc.
References getDefaultValue().
Referenced by _callSoap(), and _callUrl().
_validateFunctionName()
RpcApi::_validateFunctionName (& $name, & $serviceName) private
Definition at line 178 of file rpc_api.inc.
References D_SERVICES, and S_FUNCS.
Referenced by __call(), and FunctionExists().
DeviceInfo()
RpcApi::DeviceInfo ()
Returns
array
Definition at line 134 of file rpc_api.inc.
References D_INFO, D_NAME, D_PROPS, D_SERVICES, D_TYPE, D_URLS, PROP_NAMES, S_EVENTS, and S_FUNCS.
error()
RpcApi::error ($msg, $code = E_USER_ERROR) private
Definition at line 171 of file rpc_api.inc.
Referenced by __call(), _callRpc(), _callSoap(), and _callUrl().
FunctionExists()
RpcApi::FunctionExists ($name, $serviceName = '')
Check if function is valid.
Parameters
string $name Function name to find
string $serviceName If given then search for function only in service name
Returns
boolean True if function found
Definition at line 99 of file rpc_api.inc.
References _validateFunctionName().
FunctionList()
RpcApi::FunctionList ($a1 = true, $a2 = true)
Parameters
boolean $a1
boolean $a2
Returns
array
Definition at line 107 of file rpc_api.inc.
References D_SERVICES, and S_FUNCS.
getDefaultValue()
RpcApi::getDefaultValue ($name, $serviceName) protected
Definition at line 155 of file rpc_api.inc.
References _getFunctionParam(), V_ALLOWED, and V_DEFAULT.
Referenced by _prepareArguments().
LastError()
RpcApi::LastError ()
Returns
string
Definition at line 91 of file rpc_api.inc.
References $lastError.
SetErrorHandler()
RpcApi::SetErrorHandler ($func)
Definition at line 85 of file rpc_api.inc.
Member Data Documentation
$device
array RpcApi::$device =null private
Definition at line 10 of file rpc_api.inc.
$ErrorHandler
RpcApi::$ErrorHandler =null private
Definition at line 16 of file rpc_api.inc.
$lastError
RpcApi::$lastError ='' private
Definition at line 17 of file rpc_api.inc.
Referenced by LastError().
$pass
RpcApi::$pass ='' private
Definition at line 15 of file rpc_api.inc.
Referenced by __construct(), and _callSoap().
$user
string RpcApi::$user ='' private
Definition at line 14 of file rpc_api.inc.
Referenced by __construct(), and _callSoap().
$UserVars
RpcApi::$UserVars = [] private
Definition at line 18 of file rpc_api.inc.
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/libs/rpc_api.inc