RpcTools 5.x Project: FritzCallmon Class Reference
FritzCallmon Class Reference
Public Member Functions
Create ()
Destroy ()
GetConfigurationForm ()
GetConfigurationForParent ()
ReceiveData ($JSONString)
RequestUpdate ()
Public Member Functions inherited from IPSRpcModule
Create ()
GetApi ()
GetApiInfo ()
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance of RpcTools .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Attributes
PROP_MISSED =>'MISSED',PROP_MESSAGES=>'MESSAGES', PROP_LINE_0=>'LINE_0',PROP_LINE_1=>'LINE_1',PROP_LINE_2=>'LINE_2',PROP_LINE_3=>'LINE_3',PROP_LINE_4=>'LINE_4',PROP_LINE_5=>'LINE_5' ]
Protected Member Functions
GetDiscoverDeviceOptions ()
GetModuleName ($name, $host)
UpdateProps ($doApply=true)
DoUpdate ()
GetPropDef ($Ident)
ProcessHookData ()
Protected Member Functions inherited from IPSRpcModule
ApplyDeviceProps ($Props)
DoUpdate ()
RunUpdate ()
GetDeviceConfig ()
CreateApi ()
CallApi (string $function, array $arguments=[])
GetDiscoverDeviceOptions ()
ApplyHost ($host, $doApply=true)
ReDiscover ()
RegisterHook ($Name, bool $Create)
ProcessHookData ()
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current Configuration.
SetStatus ($Status)
Set Module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
SetDeviceState ($State)
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the device propertys.
SetProps (int $props, $Update=true, $doApply=true)
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Overide in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
CreateVarByProp ($Prop)
CreateVarByIdent ($Ident, $CheckIdent=true)
ValidIdent ($Ident, $CheckProp=false)
CreateMissedProfile ($name)
GetPropDef ($Ident)
Returns variable definitions Must overide in your own Module.
GetModuleName ($name, $host)
IsLastInstance ($guid)
Protected Attributes
$timerDef =['ONLINE_INTERVAL'=>[1,'h']
$requireLogin =[true,true]
$showRefreshButton =true
$prop_names = [PROP_CALLLIST=>'CALLLIST'
Protected Attributes inherited from IPSRpcModule
$showLogin =[true,true]
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Overide this to configure Timers for Module ONLINE_INTERVAL checks when device is Online OFFLINE_INTERVAL checks when device is offline Parameters for Checks are [0,'s'] first are the minimum value 0 = timer disabled second are the multiplicator s = seconds, m = minutes and h are hours.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable
$online =null
if not checked Null, true if online false if host not reachable
$state =null
State cache 0=connected | 1=disconnected | 2=error.
$status = null
Status cache
$prop_names = []
Contains a List of valid Propertys Key = Property value Value = Property ident name.
Private Member Functions
doDial (string $Number)
RenderCallList ($callList=null)
doDecodeCall ($data)
Detailed Description
Author
Xavier
Definition at line 9 of file module.php.
Member Function Documentation
Create()
FritzCallmon::Create ()
See also
IPSRpcModule::Create()
Definition at line 14 of file module.php.
Destroy()
FritzCallmon::Destroy ()
See also
BaseRpcModule::Destroy()
Definition at line 42 of file module.php.
References IPSRpcModule\RegisterHook().
doDecodeCall()
FritzCallmon::doDecodeCall ($data) private
Definition at line 467 of file module.php.
References BaseRpcModule\GetStatus(), IPSRpcModule\RunUpdate(), and BaseRpcModule\SetValueByIdent().
Referenced by ReceiveData().
doDial()
FritzCallmon::doDial (string $Number) private
Definition at line 261 of file module.php.
References IPSRpcModule\$api, and IPSRpcModule\CreateApi().
Referenced by ProcessHookData().
DoUpdate()
FritzCallmon::DoUpdate () protected
See also
IPSRpcModule::DoUpdate()
Definition at line 142 of file module.php.
References IPSRpcModule\CallApi(), and RenderCallList().
GetConfigurationForm()
FritzCallmon::GetConfigurationForm ()
See also
BaseRpcModule::GetConfigurationForm()
Definition at line 50 of file module.php.
References IPSRpcModule\CallApi(), and BaseRpcModule\GetStatus().
GetConfigurationForParent()
FritzCallmon::GetConfigurationForParent ()
Definition at line 79 of file module.php.
GetDiscoverDeviceOptions()
FritzCallmon::GetDiscoverDeviceOptions () protected
See also
IPSRpcModule::GetDiscoverDeviceOptions()
Definition at line 107 of file module.php.
References OPT_MINIMIZED, and OPT_SMALCONFIG.
GetModuleName()
FritzCallmon::GetModuleName ($name, $host) protected
See also
BaseRpcModule::GetModuleName()
Definition at line 121 of file module.php.
GetPropDef()
FritzCallmon::GetPropDef ($Ident) protected
See also
BaseRpcModule::GetPropDef()
Definition at line 213 of file module.php.
References PROP_CALLLIST, PROP_MESSAGES, and PROP_MISSED.
ProcessHookData()
FritzCallmon::ProcessHookData () protected
See also
IPSRpcModule::ProcessHookData()
Definition at line 227 of file module.php.
References IPSRpcModule\CallApi(), doDial(), and IPSRpcModule\RunUpdate().
ReceiveData()
FritzCallmon::ReceiveData ($JSONString)
See also
IPSModule::ReceiveData()
Definition at line 86 of file module.php.
References doDecodeCall().
RenderCallList()
FritzCallmon::RenderCallList ($callList = null) private
Definition at line 289 of file module.php.
References BaseRpcModule\SetValueByIdent().
Referenced by DoUpdate().
RequestUpdate()
FritzCallmon::RequestUpdate ()
Definition at line 93 of file module.php.
References IPSRpcModule\RunUpdate().
UpdateProps()
FritzCallmon::UpdateProps ($doApply = true) protected
See also
BaseRpcModule::UpdateProps()
Definition at line 128 of file module.php.
References PROP_CALLLIST, PROP_MESSAGES, PROP_MISSED, IPSRpcModule\RegisterHook(), and BaseRpcModule\SetProps().
Member Data Documentation
$prop_names
FritzCallmon::$prop_names = [PROP_CALLLIST=>'CALLLIST' protected
Definition at line 222 of file module.php.
$requireLogin
FritzCallmon::$requireLogin =[true,true] protected
Definition at line 100 of file module.php.
$showRefreshButton
FritzCallmon::$showRefreshButton =true protected
Definition at line 101 of file module.php.
$timerDef
FritzCallmon::$timerDef =['ONLINE_INTERVAL'=>[1,'h'] protected
Definition at line 99 of file module.php.
PROP_MISSED
FritzCallmon::PROP_MISSED =>'MISSED',PROP_MESSAGES=>'MESSAGES', PROP_LINE_0=>'LINE_0',PROP_LINE_1=>'LINE_1',PROP_LINE_2=>'LINE_2',PROP_LINE_3=>'LINE_3',PROP_LINE_4=>'LINE_4',PROP_LINE_5=>'LINE_5' ]
Definition at line 222 of file module.php.
Referenced by GetPropDef(), and UpdateProps().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/FritzCallmon/module.php