RpcTools 5.x Project: FritzLog Class Reference
FritzLog Class Reference
Public Member Functions
Create ()
RequestUpdate ()
Public Member Functions inherited from IPSRpcModule
Create ()
GetApi ()
GetApiInfo ()
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance of RpcTools .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Protected Member Functions
GetDiscoverDeviceOptions ()
GetModuleName ($name, $host)
DoUpdate ()
GetPropDef ($Ident)
UpdateProps ($doApply=true)
Protected Member Functions inherited from IPSRpcModule
ApplyDeviceProps ($Props)
DoUpdate ()
RunUpdate ()
GetDeviceConfig ()
CreateApi ()
CallApi (string $function, array $arguments=[])
GetDiscoverDeviceOptions ()
ApplyHost ($host, $doApply=true)
ReDiscover ()
RegisterHook ($Name, bool $Create)
ProcessHookData ()
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current Configuration.
SetStatus ($Status)
Set Module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
SetDeviceState ($State)
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the device propertys.
SetProps (int $props, $Update=true, $doApply=true)
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Overide in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
CreateVarByProp ($Prop)
CreateVarByIdent ($Ident, $CheckIdent=true)
ValidIdent ($Ident, $CheckProp=false)
CreateMissedProfile ($name)
GetPropDef ($Ident)
Returns variable definitions Must overide in your own Module.
GetModuleName ($name, $host)
IsLastInstance ($guid)
Protected Attributes
$timerDef =['ONLINE_INTERVAL'=>[15,'m']
$requireLogin =[true,true]
$showRefreshButton =true
$prop_names = [PROP_LOGDATA =>'LOGDATA']
Protected Attributes inherited from IPSRpcModule
$showLogin =[true,true]
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Overide this to configure Timers for Module ONLINE_INTERVAL checks when device is Online OFFLINE_INTERVAL checks when device is offline Parameters for Checks are [0,'s'] first are the minimum value 0 = timer disabled second are the multiplicator s = seconds, m = minutes and h are hours.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable
$online =null
if not checked Null, true if online false if host not reachable
$state =null
State cache 0=connected | 1=disconnected | 2=error.
$status = null
Status cache
$prop_names = []
Contains a List of valid Propertys Key = Property value Value = Property ident name.
Detailed Description
Author
Xavier
Definition at line 8 of file module.php.
Member Function Documentation
Create()
FritzLog::Create ()
See also
IPSRpcModule::Create()
Definition at line 13 of file module.php.
DoUpdate()
FritzLog::DoUpdate () protected
See also
IPSRpcModule::DoUpdate()
Definition at line 49 of file module.php.
References IPSRpcModule\CallApi(), and BaseRpcModule\SetValueByIdent().
GetDiscoverDeviceOptions()
FritzLog::GetDiscoverDeviceOptions () protected
See also
IPSRpcModule::GetDiscoverDeviceOptions()
Definition at line 34 of file module.php.
References OPT_MINIMIZED, and OPT_SMALCONFIG.
GetModuleName()
FritzLog::GetModuleName ($name, $host) protected
See also
BaseRpcModule::GetModuleName()
Definition at line 42 of file module.php.
GetPropDef()
FritzLog::GetPropDef ($Ident) protected
See also
BaseRpcModule::GetPropDef()
Definition at line 62 of file module.php.
References PROP_LOGDATA.
RequestUpdate()
FritzLog::RequestUpdate ()
Definition at line 21 of file module.php.
References IPSRpcModule\RunUpdate().
UpdateProps()
FritzLog::UpdateProps ($doApply = true) protected
See also
BaseRpcModule::UpdateProps()
Definition at line 77 of file module.php.
References PROP_LOGDATA, and BaseRpcModule\SetProps().
Member Data Documentation
$prop_names
array FritzLog::$prop_names = [PROP_LOGDATA =>'LOGDATA'] protected
See also
BaseRpcModule::$prop_names
Definition at line 72 of file module.php.
$requireLogin
FritzLog::$requireLogin =[true,true] protected
Definition at line 27 of file module.php.
$showRefreshButton
FritzLog::$showRefreshButton =true protected
Definition at line 28 of file module.php.
$timerDef
FritzLog::$timerDef =['ONLINE_INTERVAL'=>[15,'m'] protected
Definition at line 26 of file module.php.
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/FritzLog/module.php