RpcTools 5.x Project: UTILS Class Reference
UTILS Class Reference
Static Public Member Functions
static RegisterProfileInteger ($Name, $Icon, $Prefix, $Suffix, $MinValue, $MaxValue, $StepSize)
static RegisterProfileIntegerEx ($Name, $Icon, $Prefix, $Suffix, $Associations)
static RegisterProfileBoolean ($Name, $Icon, $Prefix, $Suffix, $MinValue, $MaxValue, $StepSize)
static RegisterProfileBooleanEx ($Name, $Icon, $Prefix, $Suffix, $Associations)
static RegisterProfileFloat ($Name, $Icon, $Prefix, $Suffix, $MinValue, $MaxValue, $StepSize)
Detailed Description
Definition at line 2 of file utils.inc.
Member Function Documentation
RegisterProfileBoolean()
static UTILS::RegisterProfileBoolean ($Name, $Icon, $Prefix, $Suffix, $MinValue, $MaxValue, $StepSize) static
Definition at line 35 of file utils.inc.
RegisterProfileBooleanEx()
static UTILS::RegisterProfileBooleanEx ($Name, $Icon, $Prefix, $Suffix, $Associations) static
Definition at line 49 of file utils.inc.
Referenced by FritzStatus\Create().
RegisterProfileFloat()
static UTILS::RegisterProfileFloat ($Name, $Icon, $Prefix, $Suffix, $MinValue, $MaxValue, $StepSize) static
Definition at line 66 of file utils.inc.
Referenced by FritzHomeAuto\CreateMissedProfile().
RegisterProfileInteger()
static UTILS::RegisterProfileInteger ($Name, $Icon, $Prefix, $Suffix, $MinValue, $MaxValue, $StepSize) static
Definition at line 4 of file utils.inc.
Referenced by FritzStatus\Create(), and MediaRpc\CreateMissedProfile().
RegisterProfileIntegerEx()
static UTILS::RegisterProfileIntegerEx ($Name, $Icon, $Prefix, $Suffix, $Associations) static
Definition at line 18 of file utils.inc.
Referenced by BaseRpcModule\Create(), and MediaRpc\CreateMissedProfile().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcTools/libs/utils.inc