<?php
/**
 * @var integer OPT_USE_CACHE
 * @var integer OPT_MINIMIZED
 * @var integer OPT_PROPS_ONLY
 * @var integer OPT_SMALCONFIG
 * @var integer OPT_EVENTS
 * @var integer OPT_SAVECONVIG
 * @var integer PROP_VOLUME_CONTROL
 * @var integer PROP_MUTE_CONTROL
 * @var integer PROP_TREBLE_CONTROL
 * @var integer PROP_BASS_CONTROL
 * @var integer PROP_LOUDNESS_CONTROL
 * @var integer PROP_BRIGHTNESS_CONTROL
 * @var integer PROP_CONTRAST_CONTROL
 * @var integer PROP_SHARPNESS_CONTROL
 * @var integer PROP_COLOR_CONTROL
 * @var integer PROP_SOURCE_CONTROL
 * @var integer PROP_PLAY_CONTROL
 * @var integer PROP_CONTENT_BROWSER
 * @var integer PROP_EVENTS
 * @var array PROP_NAMES
 * @var integer OPT_REQUIRE_LOGIN
 * @var integer D_HOST
 * Host Url without port
 * @var integer D_PROPS
 * Device Propertys
 * @var integer D_NAME
 * @var integer D_INFO
 * @var integer D_TYPE
 * @var integer D_URLS
 * @var integer D_OPTIONS
 * @var integer D_SERVICES
 * @var integer S_PORT
 * @var integer S_CON
 * @var integer S_CURL
 * @var integer S_URN
 * @var integer S_FUNCS
 * @var integer S_EURL
 * @var integer S_LOWERNAMES
 * Used for URL Http calls
 * @var integer S_EVENTS 
 * Comma seperated string of service variables
 * @var integer ID_VARTABLE
 * @var integer V_TYPE
 * @var integer V_ALLOWED
 * @var integer V_MIN
 * @var integer V_MAX
 * @var integer V_STEP
 * @var integer V_DEFAULT
 */

?>