RpcTools 5.x Project: C:/IP-Symcon/modules/RpcTools/libs/xml_rpc.inc File Reference
xml_rpc.inc File Reference
Classes
class XmlRPC_Parm
class XmlRPC_Struct
class XmlRPC_Array
class XmlRPC_Date
class XmlRPC_Binary
Functions
xmlrpc_encode_request ($methodName, $args)
xmlrpc_decode ($xmlStr)
Function Documentation
xmlrpc_decode()
xmlrpc_decode ($xmlStr)
Definition at line 13 of file xml_rpc.inc.
Referenced by RpcApi\_callRpc().
xmlrpc_encode_request()
xmlrpc_encode_request ($methodName, $args)
Definition at line 3 of file xml_rpc.inc.
References XmlRPC_Parm\encode().
Referenced by RpcApi\_callRpc().